### ISSUE TITLE
Excessive re-optimization of images in "Folders to optimize"

### ISSUE THREAD

**Issue by mundschenk-at** [nosilver4u/ewww-image-optimizer#1]
When using the "Folders to optimize" feature, EWWW complains about excessive re-optimization (triggered from `wp-cron.php`). Apparently, "Folders to optimize" doesn't check if an image has already been optimized before trying again.

**Comment by nosilver4u** [comment]
EWWW checks every single time it touches an image to see if it has been modified. So, if the image has changed since the previous wp-cron run, it will optimize it again. If you want help tracking that down: https://ewww.io/contact-us/
