### ISSUE TITLE
Error renaming a file when it's folder doesn't exist

### ISSUE THREAD

**Issue by Shebo** [nosilver4u/ewww-image-optimizer#11]
Hi,
Our website is a WPMU with S3 images storage.
I'm not storing copy of images locally, and every optimization process is requiring downloading>uploading>deleting the optimized image.

I noticed an error from the rename function in those lines:
https://github.com/nosilver4u/ewww-image-optimizer/blob/05d22e4df95c4f041d2d4525d5164cd94a112dd5/common.php#L4446

https://github.com/nosilver4u/ewww-image-optimizer/blob/05d22e4df95c4f041d2d4525d5164cd94a112dd5/common.php#L4482

Apparently the code assume that the destination directory for the image is already exist, but in my use case (multisite without local directories like `wp-content/blogs.dir/1888/files/2017/11`) directories aren't exist and renaming is failing.

Please add a `mkdir` functionality to the renaming process, I attached an example below.

```php
if ( ! is_wp_error( $temp_file ) ) {
    if (!file_exists(dirname($filename))) {
        mkdir(dirname($filename), 0777, true);
    }
    rename( $temp_file, $filename );
}
```

**Comment by nosilver4u** [comment]
I think that might actually be a regression, as EWWW uses one of the core functions to retrieve the upload folder, and there's an optional parameter for that function which tells WP to create the upload folder if it doesn't exist. At some point I was going through and making sure EWWW avoided triggering the upload dir test when it wasn't necessary, but I might have accidentally gone too far on it. I'll dig into that a bit more and see what I can find.

**Comment by nosilver4u** [comment]
It does indeed need to be resolved directly in the remote_fetch function as you suspected. I've committed the fix, give it a try and let me know if you have any trouble with it: https://github.com/nosilver4u/ewww-image-optimizer/commit/770bf77825738212ffbb01ed521919fe86968a15
