### ISSUE TITLE
[Question] Is WebP generation only supported via API? Will "native" generation methods be supported eventually?

### ISSUE THREAD

**Issue by willstocks** [nosilver4u/ewww-image-optimizer#124]
**Is your feature request related to a problem? Please describe.**
Hello!
This is more a question around the generation of WebP images within EWWW - will things like `cwebp` (via Linux), imagick/imagemagick + webp, PHP GD + WebP (`imagewebp`/`imagecreatefromwebp`)

**Describe the solution you'd like**
It would be nice to make use of local resources, as opposed to API/external dependencies, if the conversion can be handled locally? For instance, using native PHP GD webp conversion?

**Describe alternatives you've considered**
WebP Express - currently no native WP Offload (S3) + Cloudfront support

**Additional context**

**Comment by nosilver4u** [comment]
Hi, cwebp is already bundled with the plugin and operates just fine in free mode!
If your webhost does not allow exec() or runs a version of Linux that is not compatible with the cwebp binary, then I'm afraid you are stuck using the API.

That said, converting files to WebP via the API is free, just requires an active API subscription from https://ewww.io/plans/
