### ISSUE TITLE
picture with webp

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#125]
picture elements with existing WebP sources seem to get mangled by JS WebP, see if we can put a stop to that.

**Comment by nosilver4u** [comment]
resolved by ignoring picture tags with 'image/webp' in them

**Comment by willstocks** [comment]
@nosilver4u - just wanted to mention that off of the back of this I'm seeing console.log's in the console still, after deploying from GitHub. I imagine these won't make their way into production, but just wanted to mention!

At the moment it's just (not sure why most are null, but never mind):

```
parsing an image: https://cdn.willstocks.com/wp-content/uploads/2019/04/Swapping-a-mouse-for-a-graphics-tablet-100x124.jpg
(index):56 webp good
(index):56 parsing an image: https://cdn.willstocks.com/wp-content/uploads/2019/03/Anne-Pro-2-100x66.jpg
(index):56 webp good
(index):56 parsing an image: https://cdn.willstocks.com/wp-content/uploads/2018/10/Cheerson-CX10-Review-100x100.jpg
(index):56 webp good
(index):56 parsing an image: null
(index):56 webp good
(index):56 parsing an image: null
(index):56 webp good
(index):56 parsing an image: null
(index):56 webp good
(index):56 parsing an image: null
(index):56 webp good
(index):56 parsing an image: null
(index):56 webp good
```

**Comment by nosilver4u** [comment]
Thanks for the reminder, I need to setup a step in the script minification that strips those out just in case I forget in the future.
