### ISSUE TITLE
Binary versions

### ISSUE THREAD

**Issue by S1SYPHOS** [nosilver4u/ewww-image-optimizer#13]
Hey there,
great plugin! Btw, which versions do you use for your binaries?

Best regards,
S1SYPHOS

**Comment by nosilver4u** [comment]
They are usually pretty recent ones, I just updated them a few weeks ago (except for jpegtran and cwebp):
optipng - 0.7.7
gifsicle - 1.91
jpegtran (stock) - 9b
pngquant - 2.11.7
cwebp - 0.6.0

**Comment by S1SYPHOS** [comment]
Thanks! FYI, [cwebp v0.6.1](https://github.com/webmproject/libwebp/releases/tag/v0.6.1) is out.
Keep up the good work,
cheers!

**Comment by nosilver4u** [comment]
Yeah, we already have v0.6.1 on the API, but I didn't want to put too many updates in one release. It's tricky enough, when you're building binaries for 5 different platforms. A couple of the others were security updates and more frequently used than cwebp, so they took priority. The builds for cwebp will be updated within the next month most likely.

**Comment by S1SYPHOS** [comment]
Alright, good to know.
