### ISSUE TITLE
compat: auto-optimize with IRSC

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#136]
The Image Regenerate & Select Crop plugin has a custom regen function, which needs a custom filter/action so that we can take care of optimization afterwards.
The author is adding it to the next release, so check for the filter when IRSC is updated and add in an hook to the resize_from_meta function.
See https://wordpress.org/support/topic/integration-with-ewww-resize-settings/

**Comment by nosilver4u** [comment]
also use their new hook to delete image records for thumbs that have been disabled/removed

**Comment by galbaras** [comment]
I've tested 5.1.2 and newly-regenerated thumbnails (with IRSC 5.2.1 == latest) are neither optimised nor converted to WEBP.

Is there any setup required other than activating the two plugins?

**Comment by nosilver4u** [comment]
Unfortunately, while all the hooks are in place with EWWW IO 5.1.2, there are places where the hooks are missing from IRSC. I've posted more detail on the original thread here: https://wordpress.org/support/topic/integration-with-ewww-resize-settings/page/2/

**Comment by galbaras** [comment]
I've just tested this and some sizes aren't getting a Webp version when regenerated with IRSC, although they are getting one when directly optimised with EWWW. This happens both when regenerating all the sizes at once and when doing it individually.

Just to confirm, the sizes that don't get a Webp version are **not** blocked from optimisation in the plugin settings.

**Comment by galbaras** [comment]
I don't see this in the changelog. Might want to let people know.  From what I see, 5.2 is doing a brilliant job integrating.

**Comment by galbaras** [comment]
EWWW now shows a warning "Compressed at a lower level than current setting" for images with regenerated thumbnails, despite having re-optimised them already. What's that about?

**Comment by nosilver4u** [comment]
I believe everything on our end was resolved in 5.1.4.

As for the "compressed at a lower level", that means the original image was compressed on a different level than what you currently have active. For example, Pixel Perfect vs. Premium or even Premium vs. Premium Plus.

If you've already re-optimized the thumbs by doing a regen, you can catch just the images with "mismatched" compression levels by using the Smart re-optimize option from the bulk optimizer.
