### ISSUE TITLE
Mozjpeg

### ISSUE THREAD

**Issue by robwent** [nosilver4u/ewww-image-optimizer#15]
Just wanted to bring this to your attention. Not sure how easy it would be to integrate or if it would bring many benefits.

https://github.com/mozilla/mozjpeg

**Comment by nosilver4u** [comment]
We use it on the API already, as it generally yields better results than stock libjpeg or libjpeg-turbo. I've never been able to get it to compile a truly static binary, so we use stock libjpeg (jpegtran) for the free lossless mode.
