### ISSUE TITLE
Blank/empty/no-name image size

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#150]
**Describe the bug**
The Resize tab recently started showing the size "- 0x0", i.e. with no name. This may be related to Image Regenerate and Select Crop, but still, EWWW Image Optimizer should not display and handle a nameless size.

**Comment by nosilver4u** [comment]
That's definitely sounds like it is coming from another plugin, but I'll double-check that it isn't something EWWW IO does as a result of a "missing" size.
In the meantime, could you please post your debug information from the Support tab of EWWW IO?

**Comment by nosilver4u** [comment]
I wasn't able to replicate it with anything related to IRSC. Tried disabling sizes in both plugins, with sync active, tried ignoring/hiding sizes with IRSC, and everything checked out fine there.
At any rate, I just pushed a commit to suppress sizes that are 0x0 if you want to test it out and see how it works for you.

**Comment by galbaras** [comment]
I think the problem was after I created a new size with IRSC, cleaned it and then deleted it. It's only happened on 2 sites, seems definitely related to IRSC itself, and I've manually reset things. I think we're good.

Thank you!
