### ISSUE TITLE
Prevent resizing of images when using WP image editor

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#151]
The websites I deal with have 3 main types of images: sliders, content and shop. Yet, they are all handled the same by WordPress and by image plugins, like EWWW Image Optimizer.

Specifically, content and shop images should be capped at a certain size, because they'll never be displayed larger, but slider images span the width of the widest displays and need to be much bigger.

On several occasions, I've had the need to resize MANY images, but keep 2 or 3 at a large size. Right now, the only way to do it is to exclude the uploads folder they're in, but that's not granular enough.

An image-specific flag, which prevents resizing, would do the trick. When that flag doesn't exist, the image is resized, which is the current situation, but when it's set (can be a single bit in some existing post meta key), the image is only optimised.

**Comment by nosilver4u** [comment]
Are you referring to the auto-srcset calculation with lazy load, or is this just the max image dimensions function?
If the latter, putting 'noresize' in the filename will prevent resizing.

**Comment by galbaras** [comment]
Only for resizing.

That's good to know, but file names are important for SEO, and I have the Media File Renamer, which automatically changes the file name to match the image title.

Also, I'm sure tomorrow I'll forget about this, but a checkbox on the media editing page can make everything much clearer, and MUCH easier to protect existing images.

Come to think of it, how would I change a file name in WordPress, while keeping all the references to it intact?

**Comment by nosilver4u** [comment]
Otherwise, you can use the filters to prevent scaling an image down during editing:
https://ewww.io/2016/07/05/changing-the-dimensions-for-resizing-images/
Or just disable the "resize existing images" checkbox once you've run the initial bulk optimize.
A checkbox might be feasible, I presume you mean something in the editor screen that says "check this box to prevent resizing by EWWW IO". Or somewhere else?

And don't even bother trying to rename existing images, that's flat out dangerous. You'd have to search for the image name in all WP tables (or most anyway) just to make sure. Even then, serialization can make a mess of things for trying to find matches.

**Comment by galbaras** [comment]
Thanks, but the filter still works on file name.

> I presume you mean something in the editor screen that says "check this box to prevent resizing by EWWW IO"

Yep. That will be perfect!

> And don't even bother trying to rename existing images...

The Media File Renamer plugin does a decent job of this, but it doesn't let you pick the file name, only matches the title, which you can edit.

**Comment by nosilver4u** [comment]
I'll mark this as an enhancement request for the checkbox feature.

As for MFR, Jordy also has a pro plugin which let's you pick arbitrary names. That's not a realm I'm at all comfortable diving into, and Jordy has an entire paragraph in the plugin description communicating the dangers of renaming files, essentially saying "take backups, don't be surprised by broken links, etc." :)

**Comment by nosilver4u** [comment]
I may just look and see if we can skip resizing entirely when an image is being edited and then saved. I think it's logical enough to assume that if someone is editing an image, they don't want it scaled further.

**Comment by galbaras** [comment]
I almost always edit uploaded images as soon as they are uploaded, but I still want them resized, if required, so that's probably not a good assumption, unless the dimensions are edited explicitly.

For me, the whole issue is about separating slides (or backgrounds) from content images, really, so whichever way you can find for this will be good, e.g. a "this is a slide" checkbox.

**Comment by nosilver4u** [comment]
okay, that's good to know, thanks for the feedback!

**Comment by galbaras** [comment]
Unfortunately, I've had a realisation about this: when I upload a new image, there should be a way to prevent it from being resized when it's optimised, even if I don't edit it.

It's never simple, is it?

Sorry.

**Comment by nosilver4u** [comment]
And with MFR, the "noresize" string won't make it to the resize check, since MFR will rename it before EWWW IO ever sees the image... I've honestly no idea what is possible in the media uploader, as far as submitting custom variables and such, guess we'll find out!

**Comment by nosilver4u** [comment]
Related to MFR, I was able to make the 'noresize' flag in the filename take effect by hooking slightly earlier when MFR is active. Although WP will still constrain everything to 2560 unless you disable that. There's probably a plugin for to disable it :)

**Comment by nosilver4u** [comment]
Moving this to https://feedback.ewww.io/b/features/p/prevent-resizing-of-images-when-using-wp-image-editor
