### ISSUE TITLE
Lazy WebP poster image replacement for videos not working

### ISSUE THREAD

**Issue by CharlieHawker** [nosilver4u/ewww-image-optimizer#153]
**Describe the bug**
We're using your _excellent_ plugin for a live site and we noticed that the WebP image replacement is not working correctly for video poster images - the browser inspector does show the correct `data-poster-image` and `data-poster-webp` attributes are set on the `video` HTML element, but the lazy loading JS code is not finding and activating the correct poster image in situ.

**To Reproduce**
1. Go to EWWW Settings in the admin area
2. Under 'Basic' - turn on lazy load.
3. Under 'WebP' - turn on JPG to WebP image replacement
4. Insert a video into a post or page, ensuring it has a poster image
5. Check the rendered video on the front-end - the poster image data- attributes should be set correctly for the video poster and the webp version of it, but there is no poster attribute on the video.

**Expected behavior**
The `load_webp.js` and its minified equivalent should be picking the JPG or WebP data- attribute and setting it as the poster attribute on the video.

**Screenshots**
Not necessary as it is a simple code bug (see additional context at the end)

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**
Not necessary as it is a simple code bug (see additional context at the end)

**Sample Images**
Not necessary as it is a simple code bug (see additional context at the end)

**Additional context**
- Problem exists in both 5.1.3 and 5.1.4 at the very least (5.1.4 being latest version at time of writing.
- Problem is caused by an incorrect `document.querySelectorAll('videos')` call which should be `document.querySelectorAll('video')`. This is on **line 569** of `wp-content/plugins/ewww-image-optimizer/includes/load_webp.js` and the minified equivalent

**Comment by nosilver4u** [comment]
Thanks for catching that! The video element support is not well-tested, as I have no samples for it on my dev site, and haven't had anyone mention plugins/code they are using.
To that end, if there is a particular plugin you are using, or a bit of sample code I could implement on my dev site, that would help us catch such errors in the future.
I'll get it fixed on master, and included in the next release for sure.
Thanks again!

**Comment by CharlieHawker** [comment]
No problem 👍 

We're using some custom ACF Content Blocks inside Gutenberg for our page building, but I've just run a test and the simplest solution you could implement in your dev site is to grab a video from [this site](https://www.sample-videos.com/) (I chose the 5Mb one) and use that with the default Gutenberg "video" block.

Then make sure you click the button to the right as shown in this screenshot once the video is inserted into the page which says "Select Poster Image":
![image](https://user-images.githubusercontent.com/498011/72820886-9b1eb380-3c67-11ea-9008-f6ea23e01f16.png)

Once you've set the poster image you should be able to see the issue on the front-end. 

A couple of gotchas I encountered:
- I did have to specify the dev site domain name in 'WebP URLs' to get the replacement happening but that may have been due to me running Apache on a non-standard port. 
- I also had to enable WebP conversion for original images (but again, that's only needed if you use the original size for the poster image).

**Comment by nosilver4u** [comment]
Ah perfect, I guess it's been a while since I even attempted to test the video element. That was nice and easy, and it works perfectly (and verified it was busted before applying the fix on my dev site)!
