### ISSUE TITLE
clear out unused db records

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#157]
It would be nice (at least for internal use) to have a function that would allow one to clean out records from the table for which the files no longer exist.
Would need warnings (or just hide it) when S3 plugins (or similar) are active.

**Comment by nosilver4u** [comment]
function is in place, needs to be hidden when offloaded media has been detected

**Comment by nosilver4u** [comment]
S3 plugin detection to hide the utility is completed, might want to tweak the UI still, but we'll see.

**Comment by galbaras** [comment]
@nosilver4u This looks like the only issue holding up the 5.2 release. Any idea when it will be complete?

**Comment by nosilver4u** [comment]
finished it yesterday already, working on some other small UI tweaks before 5.2 is ready.

**Comment by galbaras** [comment]
Love your work :)
