### ISSUE TITLE
Images not displaying when alternative webp is enabled.

### ISSUE THREAD

**Issue by MartB** [nosilver4u/ewww-image-optimizer#16]
Hey there, im using newspaper-x as theme and it generates the following image links:
```
<div class="owl-item active" style="width: 366.667px; margin-right: 20px;">
	<div class="item">
		<a href="/">
			<img width="550" height="360" src="/uploads/2017/05/04_the-world_article_04-550x360.jpg" class="attachment-newspaper-x-recent-post-big size-newspaper-x-recent-post-big wp-post-image" alt="">
		</a>
	<div class="newspaper-x-related-post-title">
		<a href="/2017/05/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit/">Lorem ipsum dolor sit amet,…</a>
	</div>
</div>
```

When i enable ewww it replaces the img tag with:
```
<noscript data-img="/uploads/2017/05/04_the-world_article_01-550x360.jpg" data-webp="/uploads/2017/05/04_the-world_article_01-550x360.jpg.webp" data-alt="&quot;" data-height="360" data-width="550" data-class="attachment-newspaper-x-recent-post-big size-newspaper-x-recent-post-big wp-post-image" class="ewww_webp">
<img width="550" height="360" src="/uploads/2017/05/04_the-world_article_01-550x360.jpg" class="attachment-newspaper-x-recent-post-big size-newspaper-x-recent-post-big wp-post-image" alt="" />
</noscript>
```

Which results in no image being displayed (only when i disable javascript)

What is going wrong here?

**Comment by nosilver4u** [comment]
Can you give me a link to the page where that code exists?

**Comment by nosilver4u** [comment]
and please enable Alt WebP temporarily so I can see exactly what it is doing?

**Comment by MartB** [comment]
@nosilver4u Did as requested see:
https://torwart-jugend.de/2017/05/odio-sapien-uta-accumsan-ut-dolor-vel/

The top image and the bottom images are.

**Comment by nosilver4u** [comment]
That site is unreachable, looks like DNS hasn't propagated across the net yet: https://www.whatsmydns.net/#A/torward-jugend.de

**Comment by MartB** [comment]
You misspelled the name in your whatsmydns link, but regardless.

Add an A record with 104.28.25.134 for torwart-jugend.de

**Comment by nosilver4u** [comment]
Aha, thought it was weird that they ALL failed on the DNS test, when I was only having sporadic issues. Tried the right address this time, and the Seattle one failed, which is the node I'm probably using, wonder if Cloudflare is having trouble. I haven't noticed problems anywhere else, but I can certainly just add it to my hosts file for testing. I'll report back in a bit.

**Comment by nosilver4u** [comment]
It looks like you may just need to prevent your JS minify/combine plugin from merging jquery. The Alt WebP script is attached to the jquery enqueue, and if that's being removed, then no images get loaded.

**Comment by MartB** [comment]
It was my jquery updater script actually haha, thanks for pointing me into the right direction.

**Comment by nosilver4u** [comment]
glad to help!
