### ISSUE TITLE
Switch to using actionscheduler

### ISSUE THREAD

**Issue by pcfreak30** [nosilver4u/ewww-image-optimizer#174]
One thing that has annoyed me recently is the fact the delicious brains processing library uses postbacks to the server to chain requests. I only ever want the processing to be done over cron.

For this reason, I propose you switch to actionscheduler.org 3 library which uses dedicated tables and can better scale as well.

At a minimum, though I would like for the current background image processing to only run via cron. While I can hack around this to prevent the web request I really don't want to need to do so.

Thanks :)

**Comment by nosilver4u** [comment]
Hi @pcfreak30 ,
There are definitely limitations to the library from DB that I've wanted to fix for a long time. However, using "async postbacks" is not one of them, and Action Scheduler uses them just the same. Their implementation may differ slightly, and they call them "asynchronous loopback requests", but it's the same idea.

The good news, is that I just completed overhauling the background processing class to use our own ewwwio_queue table that we use with the bulk optimizer/scanner. This resolves the excessive use of wp_options and transients, and ended up making it faster also (#36).

There were several other improvements along the way, and you'll see a release in the next couple weeks: https://github.com/nosilver4u/ewww-image-optimizer/milestone/10

**Comment by pcfreak30** [comment]
```However, using "async postbacks" is not one of them, and Action Scheduler uses them just the same. Their implementation may differ slightly, and they call them "asynchronous loopback requests", but it's the same idea.```

I am aware they are using the async library and that alone I don't see as bad, but the background class ends up doing daisy chains, shows up in newrelic and I would like to just see cron handle on (via Unix cron or similar).

While I get that a lot of queue systems are designed around web-based background tasks, my focus is having them work as real background tasks.

As a developer, I am even moving to actionscheduler for a plugin of mine that's a significant refactoring, that has multiple dedicated queues and API complexity.

Just posting my thoughts and feedback, thanks :)
