### ISSUE TITLE
Cron task ends with an empty Error: by using wp_die()

### ISSUE THREAD

**Issue by bndn** [nosilver4u/ewww-image-optimizer#186]
The `wp_ewwwio_media_optimize_cron` cron task ran with WP-CLI ends with the empty “Error:” message.

I think some background process functions (`maybe_handle()` and `handle()`) should not ends with wp_die() as described in the WordPress Code Reference https://developer.wordpress.org/reference/functions/wp_die/

I use EWWW Image Optimizer 5.4.0 in a multisite WordPress. Tasks run with WP-CLI and this script https://bjornjohansen.no/wordpress-cron-wp-cli

Thank you!

**Comment by nosilver4u** [comment]
Thanks for reporting that! Normally such an issue would never be visible, but I'll update any of the background processing classes to make sure they die silently when finished.

**Comment by nosilver4u** [comment]
fixed in latest commit
