### ISSUE TITLE
Latest WP Offload Media (2.4) is causing a fatal error

### ISSUE THREAD

**Issue by chriselkins** [nosilver4u/ewww-image-optimizer#188]
After installing and activating the latest WP Offload Media (version 2.4), EWWW is now producing a fatal PHP error.

[15-Jul-2020 06:14:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Amazon_S3_And_CloudFront_Pro::get_provider() in /sites/***masked***/wp-content/plugins/ewww-image-optimizer/classes/class-eio-base.php:497
Stack trace:
#0 /sites/***masked***/wp-content/plugins/ewww-image-optimizer/common.php(10202): EIO_Base->content_url()
#1 /sites/***masked***/wp-includes/class-wp-hook.php(287): ewww_image_optimizer_options('singlesite')
#2 /sites/***masked***/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /sites/***masked***/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /sites/***masked***/wp-admin/admin.php(254): do_action('settings_page_e...')
#5 /sites/***masked***/wp-admin/options-general.php(10): require_once('/sites/bodyshop...')
#6 {main}
  thrown in /sites/***masked***/wp-content/plugins/ewww-image-optimizer/classes/class-eio-base.php on line 497

**Comment by nosilver4u** [comment]
We've already committed a fix to GitHub, and will be releasing it later today, thanks for reporting!
