### ISSUE TITLE
Option to disable lazyload noscript fallback

### ISSUE THREAD

**Issue by mheiduk** [nosilver4u/ewww-image-optimizer#189]
Hi,

thanks for the plugin, helps a lot for optimizing images! Below a feature request, which would be easy to implement:

**Is your feature request related to a problem? Please describe.**
A comparison-slider script isn't executing due to the noscript tags.

**Describe the solution you'd like**
An option to disable the noscript fallback partially or even completely.

**Describe alternatives you've considered**
Disabling lazyload for the comparison-sliders, but would be nice to have lazyload there too.

Best,
Marc

**Comment by nosilver4u** [comment]
Hi @mheiduk, we might need to see this in action, but that seems very odd for a slider to choke on noscript tags. Seems more likely it just can't handle lazy load in the first place. Could you please provide detail on how you confirmed it was specifically the noscript tags causing problems?

**Comment by nosilver4u** [comment]
closing as we can't fix this without more information
