### ISSUE TITLE
Support conversion of images to AVIF

### ISSUE THREAD

**Issue by e2-robert** [nosilver4u/ewww-image-optimizer#198]
A new image format - AVIF - has landed recently and is already supported by Chrome 85+ & in Firefox Nightly.

Its promises are big and the savings can be huge. What about supporting it the same way like WebP? Converting images to AVIF and delivering it to browsers where supported.

See also:
* https://jakearchibald.com/2020/avif-has-landed/
* https://caniuse.com/avif
* https://github.com/libgd/libgd/issues/557

**Comment by nosilver4u** [comment]
Thanks for the additional references @e2-robert! We already have a feature request for AVIF here: https://feedback.ewww.io/b/features/p/support-of-avif
