### ISSUE TITLE
CE options changed

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#199]
It seems CE changed the way their options are defined, so we'll need to update our check here: https://github.com/nosilver4u/ewww-image-optimizer/blob/6e220fcce30716754fab9246d8ff3adc5c781597/common.php#L334

**Comment by coreykn** [comment]
I was unaware that this was used by a plugin for integration, so I'll add some backwards compatibility for this. My apologies for introducing this on your end. I'd be happy to help find the best integration going forward. I'm unsure when the above is being called, but is `get_option()` available here? That will help me know how I'd recommend fixing this.

**Comment by The-Web-Mechanic** [comment]
Thank you both for working together on this!

Looking for a fix and update on either or both plugins!

Thanks!

**Comment by nosilver4u** [comment]
Yeah, get_option() is definitely available, it's called on the EWWW IO settings page, and also in the output buffer callback function used for our WebP parsing/rewriting functions: if CE's WebP feature is enabled, EWWW IO's WebP rewriters are blocked from running.

**Comment by coreykn** [comment]
Here are a couple examples in case it helps. If you want to use `get_option()`:

```
function ewww_image_optimizer_ce_webp_enabled() {
	if ( class_exists( 'Cache_Enabler' ) ) {
		$ce_options = get_option( 'cache_enabler', array() );
		if ( ! empty( $ce_options['convert_image_urls_to_webp'] ) ) {
			ewwwio_debug_message( 'Cache Enabler webp option enabled' );
			return true;
		}
	}
	return false;
}
```

If you want to use [`Cache_Enabler_Engine::$settings`](https://github.com/keycdn/cache-enabler/blob/334dcf957cc67537b247193eb3f91339a6608787/inc/cache_enabler_engine.class.php#L26-L35):

```
function ewww_image_optimizer_ce_webp_enabled() {
	if ( class_exists( 'Cache_Enabler' ) ) {
		if ( ! empty( Cache_Enabler_Engine::$settings['convert_image_urls_to_webp'] ) ) {
			ewwwio_debug_message( 'Cache Enabler webp option enabled' );
			return true;
		}
	}
	return false;
}
```

I've updated it a little bit to add validation to ensure the setting being checked, which is now `convert_image_urls_to_webp`, is actually available (it always should be but just in case). Or if more specific checks are preferred it can be checked that it's set and true.

**Comment by coreykn** [comment]
You're welcome @nosilver4u. We'll release backwards compatibility for this in a few hours so please feel free to take as much time as you need. 🙂

**Comment by nosilver4u** [comment]
Thanks, greatly appreciated as I'm still wrapping up a couple things for the 5.8 release!
I did push a fix to GitHub at least, so marking this as closed now. Thanks again for all your help!
