### ISSUE TITLE
Cannot restore originals

### ISSUE THREAD

**Issue by MediaMaquina** [nosilver4u/ewww-image-optimizer#203]
**Describe the bug**
When i optimize an image in the media library (list view) it does it, but there's no option to restore originals.
![no](https://user-images.githubusercontent.com/8179611/98867311-a5b46e80-246e-11eb-8247-783838b11cdf.png)

**To Reproduce**
1. Go to media library
2. Click on optimize an image
3. No option to restore original appears.

**Expected behavior**
It should give an option to restore original.

**Screenshots**
New image uploaded, and optimized.
![Untitled](https://user-images.githubusercontent.com/8179611/98867113-4fdfc680-246e-11eb-9305-ca70fda8fb3c.png)

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**

**Sample Images**
All images.

**Additional context**
I have also tried to go to tools to restore, also no option there.
![tools](https://user-images.githubusercontent.com/8179611/98867450-d4cae000-246e-11eb-958e-397a70ca5270.png)

I went to FTP hoping for a copy of the originals with the prefix "-original.png" or something, but there's no such thing, maybe it saves them elsewhere? Did it really delete them?

**Comment by nosilver4u** [comment]
That option is only for converted images, which is why it's on the Convert tab.
Optimized images are only backed up if you have an API key active with the Backup Originals option enabled (with the API, backups are stored on our servers to conserve disk space.

**Comment by MediaMaquina** [comment]
Only for converted, got it!!

Quick question so i don't spam with a new topic.
I noticed if i set "Resize Images" max width and height. And upload a large image it does resize it, but doesn't also optimize it. How can i make it do both things?

**Comment by nosilver4u** [comment]
EWWW IO always does both by default. The only way to even turn off auto-optimize is with on of the overrides. Of course, with asynchronous mode, optimization doesn't happen immediately, it might take a minute or two. And if you clear the queue (like you did at least once), then you have to manually optimize the images. Since this is going over into support topics, please use https://ewww.io/contact-us/ for any additional questions.
