### ISSUE TITLE
String mistyped

### ISSUE THREAD

**Issue by f-to** [nosilver4u/ewww-image-optimizer#208]
In file classes/class-ewww-nextgen.php line 31562 :
ewww-image-optimmizer must be replaced by ewww-image-optimizer

**Comment by nosilver4u** [comment]
Thanks for reporting that! I just fixed it in another file, so I'm going to have to widen the search and make sure it isn't in any other files.

**Comment by nosilver4u** [comment]
fixed in latest commit
