### ISSUE TITLE
Large uploads cause 500 error (on non image files)

### ISSUE THREAD

**Issue by alancwoo** [nosilver4u/ewww-image-optimizer#210]
**Describe the bug**
When uploading large files (250mb and above - non image files - mp4, zip files), `async-upload` returns a 500 error:

> There has been a critical error on your website. Please check your site admin email inbox for instructions.

and the uploader shows:

> Unexpected response from the server. The file may have been uploaded successfully. Check in the Media Library or reload the page.

**To Reproduce**
1. Create a large file to test with `truncate -s 250M test-upload.zip`
2. Go to media library and upload
3. See error

**Expected behavior**
File is uploaded and added to library

**Additional context**
All of my nginx/php settings are correct, the file is uploaded and sits in the uploads folder, but is not added to the media library.

It works whenever I disable the `ewww image optimizer` plugin.

I am using:

- Image Optimizer `5.8.2`
- Wordpress `5.6`
- PHP `7.3.25` with `memory_limit 2048M`
- imagick `3.4.4`

I'm wondering why it's happening with non-image files anyhow?

**Comment by nosilver4u** [comment]
That is definitely strange, I'll see if I can reproduce it to track down where that happens in the process. The plugin doesn't do anything with non-image files except check to see that they ARE non-image files, so it's a bit unexpected.

**Comment by nosilver4u** [comment]
I tried it just now with the latest version of the plugin, PHP 7.4.3, and whatever version of imagick is bundled with that, and got no errors on a 250MB file.
I even decreased my memory limit to 512M, and still no errors. If you are still able to reproduce this error, please check your server error logs to see if we can find the exact error.

**Comment by alancwoo** [comment]
@nosilver4u Thank you I really appreciate your help, unfortunately we still encountered this error with the plugin activated as of a few days ago (with the latest version). Upon disabling the plugin, I'm able to upload again.

I'll see if I can dig anything up in the server logs but seem to remember looking before and finding nothing of use. I'll test again and give it another look.

**Comment by nosilver4u** [comment]
You might also try some of the WP debugging constants while you're trying to get data in the logs: https://wordpress.org/support/article/debugging-in-wordpress/

**Comment by nosilver4u** [comment]
If you ever find more info on this, let me know and I'll reopen this issue.
