### ISSUE TITLE
Missing width and height for inline/data base64 image

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#212]
This is on a site with both JS and Picture delivery of WebP images. See [here](https://www.ronitbaras.com/).

Google Lighthouse is listing the inline/data Base64 image in the `srcset` of `picture` tags as not having width and height and suggests "Set an explicit width and height on image elements to reduce layout shifts and improve CLS".

Since the `img` tag has a different placeholder image, why is the inline/data image even needed?

Since the Picture tag can be written in PHP, why not populate the `srcset` with those already, instead of putting them in `data-srcset` and then moving them with script?

**Comment by galbaras** [comment]
Looks like this is the case even when JS WebP is turned off.

**Comment by nosilver4u** [comment]
I'm not seeing the `picture` markup there right now, did you turn it off?

At any rate, what I think you're seeing is the result of the lazy load placeholders. EWWW IO shouldn't use placeholders for WebP delivery otherwise.

> Since the img tag has a different placeholder image, why is the inline/data image even needed?

If we only put a placeholder on the img, then the picture element won't be lazyloaded, since the img tag is only the fallback for (old) non-picture browsers.

**Comment by galbaras** [comment]
Yes, I turned it off, because with JS-only, I'm getting better speed and accessibility scores.

I agree about lazy load placeholders. However, only the `picture` tag uses an inline/data image, which is the one causing my layout shift.

Why not put the PNG/WebP placeholder in the `srcset` attribute of the `picture` tag instead of the inline/data thingie, which isn't in the correct dimensions? If you recall, the reason for generating and using those placeholders was precisely to prevent layout shifts and enable calculations based on correct aspect ratios.

These properly-sized placeholders are one of the reasons I recommend EWWW for lazy loading over other options, so I'm not sure why this isn't the way the Picture method works too.

BTW, when Picture is enabled with JS, is there less JavaScript code, relative to JS-only?

**Comment by nosilver4u** [comment]
I had a similar thought myself last night, that the picture elements should be using "right-sized" placeholders if at all possible. I'll put that on the todo list.

When Picture mode is enabled with JS WebP, the amount of JS code is the same as JS-only mode.

**Comment by galbaras** [comment]
> I had a similar thought myself last night, that the picture elements should be using "right-sized" placeholders if at all possible. I'll put that on the todo list.

Awesome. Thank you. I hope this will do the trick.

> When Picture mode is enabled with JS WebP, the amount of JS code is the same as JS-only mode.

That's weird, since it doesn't need to do as much. the `picture` tag should take care of much of the functionality. Reducing the script size will likely benefit site performance.

**Comment by nosilver4u** [comment]
The JS itself is only 4kb, and inlined directly into the page. So creating a separate file to maintain just to go with picture mode seemed a lot more work than it's worth (saving 1-2kb).

**Comment by galbaras** [comment]
I've just bumped into something very important. Google now measures something called Largest Contentful Paint (LCP), and lazy loading seems to make this worse! See [here](https://stackoverflow.com/questions/63962906/largest-contentful-paint-increased-dramatically-when-using-lazyload#:~:text=LCP%20measures%20when%20the%20largest,of%20an%20image%20is%20showing.).

This means that the EWWW lazy loading feature should avoid images "above the fold". When this is done in JS, it should be easily detectible, particularly when placeholders are properly sized.

When done in PHP, you can use heuristics, such as not lazy loading the first content image, the first featured image, and images in the header.

Doing this also helps solve the need for properly sized placeholders, because they're not needed any more above the fold and their size becomes a moot point.

**Comment by nosilver4u** [comment]
Indeed, that is a concern, but the EWWW IO lazy loader helps with auto-scaling and WebP support also. There is a filter already that allows you to skip a specified number of images from lazy loading: eio_lazy_fold. It defaults to 0, and you can increase it to any value you like. I've not specifically tested what would happen with JS WebP if you didn't lazy load an image. I assume it would get the original JS WebP treatment, but would be interesting if you could test it out and make sure.

**Comment by galbaras** [comment]
When both JS WebP and Picture turned on, I don't see any difference even when the filter returns 15. The HTML looks the same and the output in the Network tab looks identical.

With JS WebP only, I can see fewer placeholders, but, amazingly, all the numbers seem better when the filter isn't used.

I guess we're back to using properly-sized placeholders.

OR ... here's a crazy idea:

Let's say my image is 726x484. You already know this in PHP. The ratio of height to width is 66.6666666667%. So you can add `bottom-padding: 66.6666666667%;` to the `picture` tag, and then style `picture.lazyloaded` with `bottom-padding: 0;`, so that when the script adds the class `lazyloaded` (or whatever, really) to the `picture` tag, it only shows the image where the padding was.

**Comment by nosilver4u** [comment]
I think the properly-sized placeholders will be a cleaner fix, but one other thing I'm planning to work on is filling in width/height attributes.
From what I've been researching, if we do already know the width/height via PHP, that's the cleanest method for preventing layout shift. I think it would work even with 1x1 placeholders. If someone overrides it with CSS and causes another shift, that's on them, but I think we can catch a lot of low-hanging fruit with width/height attributes.

**Comment by nosilver4u** [comment]
Also just realized we have this: https://feedback.ewww.io/b/features/p/right-sized-placeholders-for-picture-source-elements
So it already was on the todo list, I just haven't gotten that far down yet :)
