### ISSUE TITLE
Search paths for conversion binaries are inconsistent, leading to failure to execute from /usr/local/bin/

### ISSUE THREAD

**Issue by Sentynel** [nosilver4u/ewww-image-optimizer#214]
**Describe the bug**
Webp images were not being generated on my server with webp conversion enabled and a `cwebp` binary in `/usr/local/bin`, despite EWWW reporting that `cwebp` was found successfully. This turns out to be because PHP-FPM worker processes do not have an explicit `$PATH` set, and PHP and `nice` use different defaults in this case. PHP's default search path includes `/usr/local/bin` and so `ewww_image_optimizer_find_nix_binary()` records success locating `cwebp` _with no fully qualified path_. However, when `cwebp` is invoked to do the actual conversion, it's run via `/usr/bin/nice cwebp ...` (not the shell built-in version of nice!) which, it appears, defaults to a search path that does not include `/usr/local/bin` (but does include `/usr/bin`, so utilities installed with the system package manager etc will be run successfully).

This could be fixed by altering the `find_nix_binary()` and `tool_found()` functions to detect and return the full path when looking for a binary without a fully qualified path, or (easier) switching the search order at the bottom of `find_nix_binary()` such that the fully qualified paths are tried first and we only fall back to an unqualified path if the binary isn't found as a fully qualified path in the standard locations.

Note that this will affect any conversion binary in `/usr/local/bin`, it just happened to be `cwebp` I ran into.

**To Reproduce**
1. Run PHP without a `$PATH` environment variable (e.g. via PHP-FPM).
2. Enable webp conversion.
3. Place `cwebp` binary in `/usr/local/bin`.
4. Upload image.
5. Check for webp files.

**Expected behavior**
Webp files generated correctly.

**Screenshots**
n/a

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**
Output from `exec()` in `ewww_image_optimizer_webp_create()`: `nice: 'cwebp': No such file or directory`
Debug output from find function:
```
<b>ewww_image_optimizer_find_nix_binary()</b>
<b>ewww_image_optimizer_tool_found()</b>
testing case: w at cwebp
cwebp: 1.2.0
optimizer found
defining EWWW_IMAGE_OPTIMIZER_CWEBP
```

**Sample Images**
n/a

**Additional context**
(Why aren't I just using the system `cwebp`? Because Ubuntu's `webp-tools` package includes GUI binaries with a bunch of GUI library dependencies I didn't want to pull in.)

**Comment by nosilver4u** [comment]
I definitely think that could be worth trying to rectify. I'm thinking we can even do an is_file() on the fully-qualified paths, and then the "relative" or "$PATH-dependent" version is run last.

At any rate, I'm a little curious why you're not just using the bundled binaries? Do they not work on your particular system for some reason?
I'd be interested to know what sort of setup this is, so I can more reliably test any changes.

**Comment by Sentynel** [comment]
To be honest, I hadn't realised it bundled binaries until I was debugging this issue - it just reported that the binaries weren't available, so I installed them from the package manager. As it turns out, the problem is the bundled binaries are not executable when the plugin package is unzipped. For security reasons my PHP user doesn't have permission to write to any files that could be executed by the same user (as PHP or otherwise), so EWWWIO can't just chmod the binaries itself. I could do it manually, but they'd be clobbered by updates. I could alter the script that installs plugin updates to then go and fix the permissions if it's updated EWWWIO, but it seems easier to just use the system ones at this point!

**Comment by nosilver4u** [comment]
If you move the bundled version manually, the plugin won't overwrite them until we actually release a new version of that particular binary. It compares the filesizes, and if it matches, then it doesn't bother with the existing binaries.
The next release will have new ones, but it is often a long time between updates of the binaries themselves.

At any rate, I can see how that would be annoying to have to manually copy the binaries when you could just as easily install them via apt/yum, and that helps me understand more why some folks might not be able to run the binaries even when exec() is working otherwise.

I'll see if I can work on this more after I get the new binaries compiled: #215

**Comment by nosilver4u** [comment]
This will be included in the next release.
