### ISSUE TITLE
Linux ARM binaries for EC2 use if possible

### ISSUE THREAD

**Issue by Simpliant** [nosilver4u/ewww-image-optimizer#216]
**Is your feature request related to a problem? Please describe.**
Currently the plugin ships with .exe / solaris / linux 32bit intel etc binaries - however when enabled on linux
arm the set of jpegtran, gifsicle, optipng cannot run on EC2 linux ARM ubuntu.

**Describe the solution you'd like**
Would prefer if /wp-content/plugins/ewww-image-optimizer/binaries came with copies of
jpegtran-linux-x86 and jpegtran-linux-arm and etc... 

**Describe alternatives you've considered**
Alternatively it would require me to substitute the -linux binaries in /wp-content/plugins/ewww-image-optimizer/ with ARM copies, but on plugin updates they would probably be voided, another solve would be to load 
/wp-content/ewww/. with ARM binaries, but those get deleted and re-created on Plugin-on/Plugin-Off state.

**Additional context**
No additional context, makes it difficult to move between DEV (Mac-os), Stage (Intel-Linux), Production (Arm-64 EC2 Linux)
when we check the plugin files into GitHub especially (Mac-OS/Intel Linux) work just fine, Linux ARM gets broken on every deployment/update due to binary incompatibility.

**Comment by nosilver4u** [comment]
You can name the binaries jpegtran-custom, optipng-custom, and so on to make sure EWWW IO doesn't overwrite them.
See also https://docs.ewww.io/article/6-the-plugin-says-i-m-missing-something

I'm very hesitant to include ARM-compatible binaries due to the additional size increase of the plugin this would cause. However, you can post it as a feature request at https://feedback.ewww.io and we'll see if there is enough interest to warrant looking into this further.

All that said, I'm curious why you've chosen to use an ARM-64 platform for your production server when your staging is x86?

**Comment by Simpliant** [comment]
Thank you kindly for your response.

So to answer your last question, we just never got around to reloading the stage server to ARM EC2 linux, and the t2.small instance vs. t4g.small are same price - however production AWS EC2 prices are 50% for same performance between Intel and ARM.

Also to follow up on the binary naming/placement specifically-  if I put the ARM binaries into
/wp-content/ewww/optipng-custom it will not clobber them on "plugin-enable" - that would be perfect for now, as we propagate our wp-application via Git. (exec bits and all other would I'm comfortable with)

**Comment by nosilver4u** [comment]
Ah, that's interesting that they give such a huge price break for ARM instances, nice way to save some $!

With the binaries, anything with a -custom appended in the wp-content/ewww/ folder will not be clobbered :)
Alternatively, you could install jpegtran, optipng, gifsicle and (optionally) pngquant/cwebp directly from your package repositories using yum/apt.

**Comment by nosilver4u** [comment]
Closing for now, but if you'd like, you can log this as an official feature request at https://feedback.ewww.io
