### ISSUE TITLE
empty needles

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#221]
fix this:
PHP Warning: strpos(): Empty needle in /var/www/html/releases/1616503421/public/extensions/plugins/ewww-image-optimizer/classes/class-exactdn.php:748
It comes from $this->content_path being empty because of using custom theme/plugin/upload folders direct from the root URL.
In such cases, we can't validate anything against $this->content_path, and should probably disable the regex replacers for "all the things".

**Comment by nosilver4u** [comment]
Fix will be included in next release (6.1.0).

**Comment by maxleistner** [comment]
Still got these messages. 1GB of log file within 1 month :/ Version 6.1.7

**Comment by nosilver4u** [comment]
@maxleistner what are the exact error messages please?

**Comment by maxleistner** [comment]
```
[2021-06-23 14-27-17] PHP Warning: strpos(): Empty needle in /var/www/html/***/plugins/ewww-image-optimizer/classes/class-exactdn.php:699  @  https://***/cms/wp-admin/admin-ajax.php
```

**Comment by nosilver4u** [comment]
Oh good grief, I had it checking to see if the haystack was empty, but not the needle!
Fix just committed, you can grab the latest master branch or it'll be in 6.1.8 :)
