### ISSUE TITLE
`is_file()` tests from 6.1.0 generate "open_basedir restriction in effect" warning

### ISSUE THREAD

**Issue by andrenth** [nosilver4u/ewww-image-optimizer#222]
**Describe the bug**
The `is_file()` tests introduced in `ewww_image_optimizer_find_nix_binary()` in fbe888e causes the  "open_basedir restriction in effect" warning to appear.

**To Reproduce**
In my environment, I cannot execute the bundled binaries due to home directories being mounted with the `noexec` flag. This results in ewww searching for them in system paths, which leads to a `is_file()` call with a path outside the `open_basedir` allowed paths given as its parameter, causing the warning message to appear.

**Expected behavior**
The code should be warning-free.

Would it be feasible to remove the `is_file()` calls, leaving the code as it was before the commit mentioned above, or maybe check `open_basedir` and only call `is_file()` if the system directory is included in the allowed paths list?

**Comment by nosilver4u** [comment]
My main goal was to prevent errors from trying to access non-existent binaries, but we may be able to make that a little smarter by taking open_basedir into account. I'm going to be out of town for a while though, so I won't be able to look into this right away.

**Comment by mundschenk-at** [comment]
I've noticed the same issue. Maybe there should be a way to actively configure the search path for the various utilities? (Either constants or a WP option would be fine.)

**Comment by nosilver4u** [comment]
As I'm working through this, I discovered that it seems open_basedir doesn't affect the exec() function. My thinking at this point is to have EWWW IO obey the open_basedir restriction by default, but allow an override via a constant for the small subset of folks that fit in this box:
1. can't use the built-in binaries
2. have system-installed binaries
3. do NOT have the system-installed paths available via the $PATH for whatever user runs PHP

The constant syntax will be the same as open_basedir: /path/1/:/path/2/:/path/3/

**Comment by nosilver4u** [comment]
For future reference (though I'll add this to the docs), the override/constant will be EWWWIO_OPEN_BASEDIR. Defining it to an empty value will cause the plugin to skip the is_file() checks as suggested by @andrenth.

I've pushed the updated code to GitHub, would appreciate testing and feedback: https://docs.ewww.io/article/73-update-from-github

**Comment by nosilver4u** [comment]
6.1.2 just released with the fixes, so comment here if you still have any issues!
