### ISSUE TITLE
SVG image uploads & thumbnails

### ISSUE THREAD

**Issue by therealgilles** [nosilver4u/ewww-image-optimizer#225]
I have a small number of SVG images that I use on my site. I added support for SVG uploads (for admins only due to the security risk). I saw a warning about thumbnails not being regenerated. I clicked on Regenerate Thumbnails to see what would happen or if it would give me more information and got the following error:

```
ERROR: not authorized `/tmp/magick-3021VmsCnwB2VQX8' @ error/constitute.c/ReadImage/420
```

I guess thumbnails do not make sense for SVG files. My questions are:
• Is this going to create an error during Bulk Optimize (which seems likely)?
• Is there something I should do to make sure my SVG files do not create issues?

Thank you!

**Comment by therealgilles** [comment]
Forgot to mention that the SVG image does not appear in the media library admin view. Probably because there is no thumbnail for it.

**Comment by nosilver4u** [comment]
Since EWWW IO includes support for optimizing SVGs, that should not cause any issues for the bulk optimizer. It doesn't do the same things as a thumbnail regen, and handles them via svgcleaner (if you install it). Otherwise it just ignore SVG images.

**Comment by therealgilles** [comment]
May I ask what svgcleaner does?

Apparently this is what was missing to display SVG images in the backend media gallery:

```CSS
/* SVG in media gallery */
table.media .column-title .media-icon img {
	width: 60px;
}
```

**Comment by nosilver4u** [comment]
https://github.com/RazrFalcon/svgcleaner
--from what I understand (I'm no SVG guru), it's much like removing metadata/EXIF info from JPG images. Just stripping out extra stuff that doesn't affect the display.
