### ISSUE TITLE
Layout was forced before the page was fully loaded

### ISSUE THREAD

**Issue by consultingroupitaly** [nosilver4u/ewww-image-optimizer#229]
**Describe the bug**
EWWW Image Optimizer 6.1.5
Firefox say:
```
lazysizes.min.js:1:1741
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
```

**To Reproduce**
1. Open any page with lazy loader
2. In the Firefox console you see:
```
lazysizes.min.js:1:1741
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
```

**Expected behavior**
No warnings.

**Comment by nosilver4u** [comment]
Will be moving lazysizes.min.js to page footer, similar to other lazy loaders. Hopefully it doesn't create more issues!

**Comment by consultingroupitaly** [comment]
Sorry for the late reply, currently I don't have time to verify on all devices. 
It doesn't seems to happen on desktop but I cannot be 100% sure.
Still I thought that the Firefox warning may have some sense.

Thanks for yout work.

**Comment by nosilver4u** [comment]
No worries, I couldn't see that it was actually causing any problems, but all the other lazy loaders I checked were loading their scripts in the footer, so I figured we'd give it a try :)
