### ISSUE TITLE
SVG Placeholders doesn't work with JS WebP Rewriting without <picture> WebP Rewriting

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#230]
**Describe the bug**
The PNG placeholders were causing layout shifts, so I checked the box for "SVG Placeholders". That cleared the layout shifts, but no images were loaded until I also checked "<picture> WebP Rewriting".

My site is on CloudFlare, so I have "JS WebP Rewriting" turned on. I also have "Automatic Scaling" turned on, if this makes any difference.

This issue doesn't happen with .htaccess based WebP delivery, so I'm guessing it's something in the WebP script, possibly combined with the lazy loader.

**Comment by nosilver4u** [comment]
Hmm, I suppose the issue with PNG placeholders would be because the PNG placeholders are larger than what will be used from the srcset listing? Would you be able to check on that and confirm (or deny) my suspicion?

That's strange to see an issue with SVG placeholders and JS WebP, so I'll look into it further. Thanks for the report!

**Comment by nosilver4u** [comment]
Unable to replicate an issue with Lazy Load + Auto Scale + SVG Placeholders + JS WebP, any other ideas?
If you can replicate it on a staging site so I can inspect it live, that might help.

**Comment by galbaras** [comment]
Embarrassingly, I couldn't replicate the problem on the test site, so I tried going back to the live site and checking again, and there's no problem anymore 😱  Might have been related to caching/Cloudflare.

**Comment by nosilver4u** [comment]
That's definitely possible for it to be a caching issue, especially if you have anything doing minification/combination of JS resources. Let me know if the issue crops back up!
