### ISSUE TITLE
Using 'wp_calculate_image_sizes' filter doesn't change the image 'sizes' attribute

### ISSUE THREAD

**Issue by erip2** [nosilver4u/ewww-image-optimizer#233]
**Describe the bug**
I'm using the EWWW Image Optimizer to convert the images to webp. But, when I use the 'wp_calculate_image_sizes' in order to change the default _sizes_ attributes of the image, the < img > shown by ewww continues to keep the default ones. The < img > tag inside the <noscript> has the changed _sizes_ value to new one as it should.

**To Reproduce**
1. Enable the webp convert from the plugin
2. Add 'wp_calculate_image_sizes' filter to functions.php to change the _sizes_ value. An example:

```
add_filter( 'wp_calculate_image_sizes' , function( $sizes ) {
   $sizes = "(min-width: 1340px) 460px, (min-width: 1080px) calc(24.17vw + 141px), (min-width: 940px) 270px, (min-width: 780px) calc(26.43vw + 27px), (min-width: 720px) 285px, (min-width: 600px) calc(30vw + 75px), calc(100vw - 74px)";
   return $sizes;
}, 10, 1);
```

3. Look at the page images and their _sizes_ value.

**Expected behavior**
The converted <img> tag should have the new sizes attribute value.

**Screenshots**

Normal behaviour
![Normal behaviour](https://i.ibb.co/K5Hj8fX/output-onlinepngtools.png)

EWWW generated image
![EWWW generated image](https://i.ibb.co/SwQ1m6b/ss.png)

**Additional context**
Using WordPress 5.7.2 and EWWW Image Optimizer 6.1.7.

**Comment by nosilver4u** [comment]
Hi @erip2!
That behavior is normal and expected from the Auto Scaling feature. If you want to use your own srcset, just turn off Auto Scaling.
