### ISSUE TITLE
Incompatible with S3-Uploads v3.0

### ISSUE THREAD

**Issue by pfiled** [nosilver4u/ewww-image-optimizer#236]
S3-Uploads 3.0 has switched to namespaces, and now uses a different class name:

https://github.com/humanmade/S3-Uploads/releases/tag/3.0.0

Changing:

`class_exists( 'S3_Uploads' ) to class_exists( 'S3_Uploads\Plugin' )`

and

`method_exists ( 'S3_Uploads', 'methodname' ) to method_exists( 'S3_Uploads\Plugin', 'methodname' )`

In all locations seems to resolve the issue, but would cause issues when S3-Uploads v2 is used without additional logic.

Thank you for the great plugin!

**Comment by nosilver4u** [comment]
Thanks for reporting that, I hadn't messed with version 3 yet!

**Comment by nosilver4u** [comment]
fixed, let me know if you find any further issues!
