### ISSUE TITLE
SQL syntax error in aux-optimize.php line 973

### ISSUE THREAD

**Issue by komsitr** [nosilver4u/ewww-image-optimizer#246]
**Describe the bug**
SQL syntax error in aux-optimize.php line 973

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY attachment_id DESC' at line 1 for query SELECT attachment_id FROM wp_ewwwio_queue WHERE gallery = 'media' AND scanned = 1 LIMIT 1 ORDER BY attachment_id DESC made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->run_command_and_exit, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, EWWWIO_CLI->optimize, ewww_image_optimizer_bulk_loop, ewww_image_optimizer_get_queued_attachments

**To Reproduce**
1. Execute wp-cli `wp ewwwio optimize media`
2. See error

**Expected behavior**
No error should be thrown.

**Suggested fix**
From the https://github.com/nosilver4u/ewww-image-optimizer/commit/2f0e1c5e092e0921da6275bbb84c18016b22cfff commit, the new SQL is no longer valid.

Move `LIMIT 1` after the `ORDER BY` statement

**Comment by nosilver4u** [comment]
Thanks!
