### ISSUE TITLE
Add sharpen settings and a way to (bulk) sharpen images selectively

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#249]
**Is your feature request related to a problem? Please describe.**
Currently, the smaller the thumbnail, the more blurry it is, at least in some cases. There's also no way to optimize images visually by sharpening them, and that can be useful sometimes.

**Describe the solution you'd like**
Provide a "Sharpen" setting, which determines the level of sharpening done by default, and sharpen images accordingly when they are created.

It might be good to have separate settings for the full size image and each one of the thumbnail sizes. These should be relative to the original.

Alternatively, sharpen the full size image as per the global setting and apply reasonable sharpening settings to each thumbnail size based on best practices.

**Describe alternatives you've considered**
The following plugins have relevant features and potential code ideas:

https://en-au.wordpress.org/plugins/warp-imagick/
https://en-au.wordpress.org/plugins/better-images/

**Additional context**
I'm currently working on a fashion site, where visual clarity is paramount, but images are not as sharp as they could be, and the ability to sharpen them from the media library would be golden.

**Comment by nosilver4u** [comment]
Sorry, I need to update the feature request template to indicate that we track those elsewhere. Can you please re-post that at https://feedback.ewww.io ?

**Comment by galbaras** [comment]
The author of WP Fastest Cache has agreed to process `data-cfasync="false"` attributes. Once that's released, there won't be a need to change EWWW IO anymore.

**Comment by nosilver4u** [comment]
@galbaras I think maybe you posted that reply on the wrong issue?

**Comment by galbaras** [comment]
Oops, I think I did :D

**Comment by galbaras** [comment]
[Feature request created](https://feedback.ewww.io/b/features/p/add-sharpen-settings-and-a-way-to-sharpen-selected-images)
