### ISSUE TITLE
ewww_webp_supported script compatibility with WP Fastest Cache

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#250]
**Describe the bug**
The quick inline script to determine the browser's WebP capability (JS method) is being combined with other scripts by WP Fastest Cache when "Render Blocking Js" is enabled. The combined script is then deferred.

The result is that the script runs too late, and styles that rely on the `.web-support` class end up fetching WebP background images AFTER the JPG/PNG has already been loaded, and that's no good.

**To Fix**
Add the `data-wpfc-render="false"` attribute to the script.

**Comment by nosilver4u** [comment]
Indeed, none of the JS WebP scripts should be merged, deferred, or modified in any way. We'll need to add that in multiple locations, though I'll see if we can make that conditional so we aren't cluttering up the markup for folks who don't use WPFC.

**Comment by galbaras** [comment]
Posting in the right issue: The author of WP Fastest Cache has agreed to process data-cfasync="false" attributes. Once that's released, there won't be a need to change EWWW IO anymore.

**Comment by nosilver4u** [comment]
Can you confirm whether the small script which adds the "web-support" class to the body tag is left intact by WPFC?
That's the one inlined right after the opening `<body>` tag.

**Comment by galbaras** [comment]
Not yet, but should be from the next update. So far, all I have is an email saying "yes, I will do it and let you know. thank you so much."
