### ISSUE TITLE
Plugin breaks Hestia theme bootstrap functions

### ISSUE THREAD

**Issue by dylanirion** [nosilver4u/ewww-image-optimizer#256]
The Hestia theme loads a custom minified bootstrap 1.2.0 (can it be that old??)

This latest version (2.6.4) of EWWW breaks the navbar-fixed-top and dropdown-toggle bootstrap functionality on mobile.

**Comment by nosilver4u** [comment]
Hi @dylanirion,
Generally, the only thing in EWWW IO that could touch JS/CSS would be the Easy IO CDN. If you disable the Include All Resources function, does it resolve the problem?

**Comment by dylanirion** [comment]
I'm using WP Offload and S3, but disabling the JS rewrite for webp did the trick

The Lazy Load option now has the label "Fix: Typos in the ly load module" not sure if this is intended.

**Comment by nosilver4u** [comment]
Hmm that's strange, so either we're having JS errors somewhere with JS WebP, or altering the image markup is breaking the bootstrap stuff. Can you check the dev tools (right click, Inspect, then go to Console), and see if there are any errors there with JS WebP enabled?

I don't even know where that label would come from on lazy load, can you post a screenshot?

**Comment by dylanirion** [comment]
There is actually, I get a jquery error

```
jquery.min.js?ver=3.6.0:2 Uncaught TypeError: e.arrive is not a function
  at Object.init (script.min.js?ver=3.0.18:1)
  at HTMLDocument.<anonymous> (script.min.js?ver=3.0.18:1)
  at e (jquery.min.js?ver=3.6.0:2)
  at t (jquery.min.js?ver=3.6.0:2)
```

![ewww](https://user-images.githubusercontent.com/61515823/132860202-06163d09-8aa7-464b-a110-4746006b81dd.png)

**Comment by nosilver4u** [comment]
What is that 'script.min.js'?

**Comment by dylanirion** [comment]
Pretty sure it's the jQuery that ships with Wordpress

/wp-includes/js/jquery/jquery.min.js?ver=3.6.0

**Comment by nosilver4u** [comment]
Right, but in the middle there we have 'script.min.js' which is NOT jQuery, it's something using jQuery though.

**Comment by dylanirion** [comment]
Ah sorry, I didn't catch that! Seems it's part of the Hestia theme. A problem on their side then?

**Comment by nosilver4u** [comment]
Kind of, seems like maybe they are loading some sort of extension to the jQuery arrive method? Can you double-check that with them at least?

**Comment by dylanirion** [comment]
Sounds like they've replicated it.
