### ISSUE TITLE
Both JPG and WebP backgrounds loaded - WebP JS

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#258]
**Describe the bug**
When a style `X` has a JPG background and `.webp-support X` has a WebP background, BOTH files are loaded onto the page. My guess is that somehow, the inline script that sets the body class somehow runs after the browser has requested the JPG image.

This happens when Webp JS is active (and the page is delivered via Cloudflare, but this shouldn't make a difference. In my case, Picture WebP is also active, but I don't think this matter either).

The issue is most likely related to the timing of requests, possibly when using HTTP/2 or HTTP/3.

**To Reproduce**
1. In the page header, style an element with a JPG background and that same element with a `.webp-support` prefix with a WebP background
2. Active WebP JS (and Picture)
3. Load the page
4. Check which versions of the background were loaded in the code inspector's network tab

**Expected behavior**
Only one version of the background should be loaded, depending on whether the device supports WebP or not.

**Comment by nosilver4u** [comment]
Is that on one of the sites where you were using WPFC? If so, make sure they aren't combining or deferring the inline body script. It needs to be the very first thing in the `<body>` section, and must not be deferred in any way.

**Comment by galbaras** [comment]
I'd taken care of this already and it was definitely the first tag inside the BODY, but still loaded the both versions. BTW, I manually added `data-cfasync="false"` to this script, because 6.2.4 still didn't have that, although I can see it in the master code now.

Had to clear absolutely every cache known to man to make it work again, but it seems OK now.

Just a thought: if [this script](https://github.com/nosilver4u/ewww-image-optimizer/blob/91b2445f30d4f1d14ed9702c2e9f7e4bf0c8c035/classes/class-eio-lazy-load.php#L313) should not be deferred either, it'll be good to add `data-cfasync="false"` to it as well.

**Comment by nosilver4u** [comment]
Indeed, the snippet for LL should be updated for consistency, even though the LL script won't throw an error anymore if that is missing or loaded async.
