### ISSUE TITLE
SVG placeholder missing from first image for guests

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#266]
**Describe the bug**
When I analysed [this page](https://www.ronitbaras.com/family-matters/parenting-family/guilt-tripping-saying-sorry/) with the Lighthouse extension in an Incognito window, it showed a cumulative layout shift caused by the first content image. Sure enough, this image had no SVG placeholder (in the source code).

`<picture><source srcset="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg.webp 960w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-150x104.jpg 150w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-536x371.jpg.webp 536w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-740x512.jpg.webp 740w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-200x138.jpg.webp 200w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-360x249.jpg.webp 360w" sizes='(max-width: 960px) 100vw, 960px' type='image/webp'><img class="alignnone size-full wp-image-24567" src="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg" alt="Sad smiley" width="960" height="664" srcset="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg 960w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-150x104.jpg 150w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-536x371.jpg 536w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-740x512.jpg 740w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-200x138.jpg 200w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-360x249.jpg 360w" sizes="(max-width: 960px) 100vw, 960px" data-eio="p" /></picture>`

Thinking this might be due to caching, I checked the same page while logged in, because that's un-cached, and saw this very different tag:

`<picture><source  sizes='(max-width: 960px) 100vw, 960px' type='image/webp' data-srcset="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg.webp 960w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-150x104.jpg 150w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-536x371.jpg.webp 536w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-740x512.jpg.webp 740w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-200x138.jpg.webp 200w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-360x249.jpg.webp 360w"><img class="alignnone size-full wp-image-24567 lazyload" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 960 664'%3E%3C/svg%3E" alt="Sad smiley" width="960" height="664"   data-eio="p" data-src="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg" data-srcset="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg 960w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-150x104.jpg 150w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-536x371.jpg 536w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-740x512.jpg 740w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-200x138.jpg 200w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-360x249.jpg 360w" data-sizes="auto" data-eio-rwidth="960" data-eio-rheight="664" /><noscript><img class="alignnone size-full wp-image-24567" src="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg" alt="Sad smiley" width="960" height="664" srcset="https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry.jpg 960w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-150x104.jpg 150w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-536x371.jpg 536w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-740x512.jpg 740w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-200x138.jpg 200w, https://www.ronitbaras.com/wp-content/uploads/2021/03/sorry-360x249.jpg 360w" sizes="(max-width: 960px) 100vw, 960px" data-eio="l" /></noscript></picture>`

So I decided to check this a different way and added `?nocache` to the URL in the Incognito window, because this also bypasses the cache. The first content IMG tag had no placeholder.

Since the site is on Cloudflare, I cleared the entire cache and purged "everything" on Cloudflare. The logged out page source code still did not have the first placeholder. I've also looked at relevant Cloudflare community discussions and found that Cloudflare doesn't remove inline SVG (or NOSCRIPT) tags or inline images.

Other content images on the page have identical tags in all cases.

**To Reproduce**
1. Configure the plugin as per the screenshot below
![image](https://user-images.githubusercontent.com/7981897/144362530-10164a9c-1d60-4016-bdbd-92f0a4c5e52f.png)
2. Create a post with an image at the top, then some content, and then another image and more content
3. Publish the post and compare the image tags in the page source when logged in and when logged out

**Expected behavior**
All image tags should be identical.

**Comment by galbaras** [comment]
Sorry, this seems to be a Cloudflare issue after all. When I load the page straight from the origin server, the IMG tag seems OK.

**Comment by nosilver4u** [comment]
Huh, that's a strange bugger. I would note, that in version 6.3 we started skipping the first image in any given page as being "above the fold". That, of course, brings the potential for increased CLS if image dimensions are missing. I don't remember off-hand how that works for picture elements though.

**Comment by galbaras** [comment]
When I'm logged in, or when I go directly to the origin server, or when I test on a site clone that isn't on Cloudflare, the SVG placeholder is clearly there, and I think it should be. I think skipping the first image only makes sense when using PNG placeholders, because they causes a CLS, but an inline SVG shouldn't.

Just a thought: an inline PNG wouldn't either, bug if SVGs work, then why bother?

**Comment by nosilver4u** [comment]
Yeah, I'm not 100% set on the current behavior for sure. But Google was starting to ding folks for lazy loading above-the-fold images... I think there might be a way we can prevent Google from complaining and still maintain the auto-scaling ability for above-the-fold images, since that's the largest downside to skipping any images from lazy load.

At any rate, we do already have inline PNG images as of 6.2.2, because SVGs don't work with all themes. Though we've made the SVG option safer by only using it when height and width attributes are set, I now prefer the inline PNG option myself.

**Comment by galbaras** [comment]
Thanks for that. Cloudflare removes inline PNGs as well 😢

**Comment by nosilver4u** [comment]
Hmm, strange, I'll have to keep an eye on that. Just to make sure it isn't from EWWW IO itself, you can set the "above the fold" threshold/counter to 0 in your wp-config.php:
define( 'EIO_LAZY_FOLD', 0 );

**Comment by galbaras** [comment]
That's not it. Without this constant, compare [this post](https://www.ronitbaras.com/emotional-intelligence/personal-development/talent-success-almost-made-olympic-team/) (on the live site, delivered via Cloudflare) to [this one](https://dev.get-business-online.com/ronitbaras/emotional-intelligence/personal-development/talent-success-almost-made-olympic-team/) (on a test clone, delivered directly).

In both cases, you can add `?nocache` to the URL for an un-cached and un-optimised version, which is easier to read.

**Comment by nosilver4u** [comment]
I probably just waited too long, but I don't see any lazy loading on the first image in the page (the "flying high" featured image at the top).

**Comment by galbaras** [comment]
Adding `define( 'EIO_LAZY_FOLD', 0 );` to wp-config.php resolved this problem. Not sure why there was a difference between logged in and guest, but I feel like Google treatment of CLS means that when inline placeholders are used, every image should have one, rather than skipping the first one, [which EIO does now](https://github.com/nosilver4u/ewww-image-optimizer/blob/3de132b9e9694e2da16262f7a152b25f16801b67/classes/class-eio-lazy-load.php#L327).

**Comment by nosilver4u** [comment]
That makes sense that it would be from the new lazy fold default of 1, though that IS strange for it to be different for guests unless the page cache wasn't getting purged.
At any rate, I'm inclined to agree with you on the CLS issues. Theoretically, if an image has height/width set, the CLS would be unaffected, but detecting that would add a whole different level of complexity there.
I'll consult a bit more with Adam on this, but my inclination is to set it back to 0 in the next release.
