### ISSUE TITLE
Plugin Overrides text is out of date

### ISSUE THREAD

**Issue by galbaras** [nosilver4u/ewww-image-optimizer#267]
When clicking on the Override tab heading in the plugin's settings page, there's mention of EWWW_IMAGE_OPTIMIZER_DELAY, EWWW_IMAGE_OPTIMIZER_NOAUTO, which no longer exist, and perhaps others.

**Comment by nosilver4u** [comment]
The first section of that doc is specifically for settings which no longer exist in the UI (or never did, like NOAUTO), but can only be set via constant.

**Comment by galbaras** [comment]
Judging by the fact that they aren't mentioned in the plugin code, I don't think they can be set. In fact, I know that EWWW_IMAGE_OPTIMIZER_DELAY was removed in favour of a bulk optimizer setting, because that's in the changelog.

**Comment by nosilver4u** [comment]
In the code the overrides are usually lower-case. We check for the constant values (in upper-case) in the ewww_image_optimizer_get_option() function. You'll find ewww_image_optimizer_delay in the bulk.php file (among others).
