### ISSUE TITLE
EWWW + WooCommerce conflict

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#27]
See https://github.com/woocommerce/woocommerce/issues/21634#issuecomment-434012213
Somehow Woo is triggering re-optimization of full attachments, and causing quite a bit of load.

**Comment by dotcominfo** [comment]
Glad to hear the issue is being explored. I've been working through over utilization issues on a client site and this might end up being a big part of it. It would explain alot. We didn't have this issue when we first launched the site, and then it started happening again. Seems like running a prior version of the plugin (from early September) might also be a way to go (instead of disabling the plugin).

**Comment by nosilver4u** [comment]
Some of the old releases are here: https://github.com/nosilver4u/ewww-image-optimizer/releases
Most of them should be on here for the 4.x series: https://wordpress.org/plugins/ewww-image-optimizer/advanced/

If any of those fixes anything, I'd be surprised, as the background/async stuff that appears to be involved in the problem hasn't changed in the 4.x releases.
It's more likely that having EWWW disabled suppresses the issue, and then re-enabling it causes things to operate normally until there is a backlog again.

**Comment by nosilver4u** [comment]
Confirmed that Woo is (re)generating thumbs on the fly, then calling wp_generate_attachment_metadata(), which is where EWWW IO gets triggered.
This happens in several areas:

1. when using the customizer to modify the size of images (I'm guessing for product pages, but could also happen for any WC displays).
2. when you change themes, wow, that could be huge!
3. on-demand when viewing a page where the expected size does not yet exist. Typically after making adjustments with the customizer.

**Comment by nosilver4u** [comment]
So the first problem (which occurs in 1 & 2), is that WC queues all images for background thumb regeneration. When WC finishes each one, it triggers EWWW IO automatically. And this is where things go a bit sideways. WC is clever enough to add everything to the queue, and then run dispatch() once (it uses the same class as EWWW IO for async/background processing).

EWWW IO doesn't have that luxury, as it's being called each time WC finishes, and ends up calling dispatch, which is where an admin-ajax.php POST request happens, over and over and over.

So I think we need to figure out a way to recognize the WC regen process, and prevent the dispatch() from running so many times. Or at all, since wp_cron will kick it off within 5 minutes anyway.

**Comment by nosilver4u** [comment]
Alright, the latest commits resolve two issues:
1. If there are items in the EWWW IO background queue, dispatch() will not be called, since the queue is likely already running. Otherwise, dispatch() creates extra (unnecessary) calls to admin-ajax.php. To be safe, I've set it to call dispatch() when the queue size is smaller than 5, which should hardly cause anything like "excessive" calls to admin-ajax.php.
2. As with any thumbnail regen, EWWW IO needs to disable the WP_Image_Editor extensions, so that optimization doesn't happen prematurely and cause timeouts for the regen task.
