### ISSUE TITLE
Optimization results are not shown for translated media via Polylang

### ISSUE THREAD

**Issue by ocean90** [nosilver4u/ewww-image-optimizer#274]
**Describe the bug**
Just like WPML, Polylang has also a feature to duplicate media attachments. While the image is optimized the list table shows the results only for one of the images. Example:

<img width="1557" alt="" src="https://user-images.githubusercontent.com/617637/150565219-a08b7523-b807-4dec-8446-7ff50e4c0cd2.png">

The result is only attached to the French translations (even through the German one was the first uploaded, might be a bug somewhere else).

For context: The file is always the same, it's just the post and post meta that's duplicated.

**To Reproduce**
1. Install Polylang Pro and activate the media duplicate feature
2. Upload an image
3. Go back to the list table and notice that only one entry is shown as optimized.

**Expected behavior**
The results are for all translated items the same.

**Additional context**
The media duplicate feature is actually a feature of the Pro version of Polylang so I don't expect that EWWW supports this by default. My idea would be that a generic `ewww_image_optimizer_get_primary_wpml_id()` and `ewww_image_optimizer_get_wpml_results()` function is created. These functions would have a filter which by default are used to implement the support for WPML. This would allow me (or Polylang cc @Chouby) to extend this with support for Polylang.

@nosilver4u Is that something you're open to? Happy to provide a PR for this.

**Comment by nosilver4u** [comment]
Hi @ocean90,
I would definitely be open to that, especially if you could do a PR! That would save me a ton of time since I've not used their Pro version before and only briefly tested some things on the free version way back.

**Comment by ocean90** [comment]
@nosilver4u Thank you for working on this! I have found two issues with the `ewwwio_translated_media_ids` filter. See #290 for the details. Thanks for looking into it.

**Comment by ocean90** [comment]
This is the integration for Polylang I'm now using. Not sure if that's something that should be part of this plugin or Polylang. @nosilver4u What do you think?


```php
/**
 * Sets the primary translation ID for an attachment.
 *
 * @param int $id Attachment ID.
 * @return int Translated attachment ID.
 */
function set_ewwwio_primary_translated_media_id( int $id ): int {
	if ( function_exists( 'pll_get_post' ) && function_exists( 'pll_default_language' ) ) {
		$id = pll_get_post( $id, pll_default_language() ) ?: $id;
	}

	return $id;
}
add_filter( 'ewwwio_primary_translated_media_id', __NAMESPACE__ . '\set_ewwwio_primary_translated_media_id' );

/**
 * Sets results for all attachment translation replicates.
 *
 * @param array $translations List of attachment IDs.
 * @param int   $id           Attachment ID.
 * @return array List of attachment IDs.
 */
function set_ewwwio_translated_media_ids( array $translations, int $id ): array {
	if ( function_exists( 'pll_get_post_translations' ) ) {
		$translations = array_values( pll_get_post_translations( $id ) );
	}

	return $translations;
}
add_filter( 'ewwwio_translated_media_ids', __NAMESPACE__ . '\set_ewwwio_translated_media_ids', 10, 2 );
```

**Comment by nosilver4u** [comment]
Hmm, I could just about go either way on that, though if it's done in Polylang, then the code becomes leaner since they can get rid of the function_exists() checks. I would recommend asking the Polylang devs if they are willing to add it. If they don't want to add it directly in Polylang, then go ahead and submit a pull request for EWWW IO.
