### ISSUE TITLE
PHP Warning:  Trying to access array offset on value of type bool in .../wp-content/plugins/ewww-image-optimizer/unique.php on line 1988

### ISSUE THREAD

**Issue by consultingroupitaly** [nosilver4u/ewww-image-optimizer#275]
`PHP Warning:  Trying to access array offset on value of type bool in .../wp-content/plugins/ewww-image-optimizer/unique.php on line 1988`

Here: https://github.com/nosilver4u/ewww-image-optimizer/blob/master/unique.php#L1987
the function 

> posix_getgrgid

 return false on failure but it isn't checked so on the following line there is the warning.

**Comment by nosilver4u** [comment]
Wow, that's surprising to see a failure there, but we should indeed check for false before handling the result. Thanks for reporting that!

**Comment by consultingroupitaly** [comment]
Thanks.
