### ISSUE TITLE
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CURRENT_TIMESTAMP'

### ISSUE THREAD

**Issue by consultingroupitaly** [nosilver4u/ewww-image-optimizer#277]
**Describe the bug**

This is what I get in the log:
`WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CURRENT_TIMESTAMP' at line 1 for the query ALTER TABLE wp_ewwwio_images ALTER updated SET DEFAULT CURRENT_TIMESTAMP done by require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, ewww_image_optimizer_admin_init, ewww_image_optimizer_upgrade, ewww_image_optimizer_install_table`

**To Reproduce**

1. Just update to the latest version of the plug-in

**Comment by nosilver4u** [comment]
Ugh, we were supposed to be done with that... Please post your site health info so we can see more specifics on your database setup.

**Comment by consultingroupitaly** [comment]
**WordPress**
Name | Value
-- | --
Versione | 5.9.1
Lingua del sito | it_IT
Lingua utente | it_IT
Fuso orario | Europe/Rome
Questo sito utilizza HTTPS? | Sì
Questo è un multisito? | No
Chiunque può registrarsi su questo sito? | No
Questo sito sta scoraggiando i motori di ricerca? | No
Tipo di ambiente | production
Comunicazione con WordPress.org | WordPress.org è raggiungibile

**Database**
Name | Value
-- | --
Estensione | mysqli
Versione del server | 5.6.51-91.0-log
Versione del client | mysqlnd 7.4.24
Prefisso tabella | wp_
Charset del database | utf8mb4
Collation del database | utf8mb4_unicode_520_ci
Dimensione massima consentita per i pacchetti | 67108864
Numero massimo di connessioni | 10000

**Comment by consultingroupitaly** [comment]
I always update everything I could but since mysql is handled by the hosting I cannot do it unfortunately.
Thanks.

**Comment by nosilver4u** [comment]
I would recommend asking your web host to get that updated ASAP, or move your sites to a new server. Though if they haven't already updated MySQL at this point, I suspect they have no plans to do so. Shared hosting I'm guessing?

**Comment by consultingroupitaly** [comment]
Yes, they are just incredibly late in update everything.
The problem is that the hosting is connected to domain/hosting/e-mail/PEC so changing it is a long process.

**Comment by nosilver4u** [comment]
Ugh, that's no fun, and switching hosts is definitely not a ton of fun if you have everything connected to them. Sometimes, it's just their "old" servers that aren't up to date, and they might be able to move you to a newer server that's got more recent software available without too much hassle (on your end at least). If they have decent internal tooling, they should be able to do that even more easily if they are your registrar and DNS provider too.

**Comment by nosilver4u** [comment]
You can grab the latest to confirm the fix from here: https://docs.ewww.io/article/73-update-from-github

**Comment by consultingroupitaly** [comment]
I have updated it and I do not get any error but to be sure it worked is there something to look in the database?

**Comment by nosilver4u** [comment]
If it worked, there should have been an admin notice that the db needed to be upgraded. Either way, you can check the default value for the 'updated' column. Both the default and the "ON UPDATE" values should be set to CURRENT_TIMESTAMP.

**Comment by consultingroupitaly** [comment]
I don't have any admin notice but the 'updated' column is correct.
See:
![DB](https://user-images.githubusercontent.com/44967141/158608782-dfbcdcfd-d70b-4da4-898e-a6312ac48487.png)

**Comment by consultingroupitaly** [comment]
@nosilver4u: I have been able to update the database although it is a very cumbersome procedure of buy new DB (get price set to 0 by support team), move the DB content on the new DB and wait the expiration of the old ones.
