### ISSUE TITLE
No spacing between tag attributes breaks display.

### ISSUE THREAD

**Issue by LeoHorde** [nosilver4u/ewww-image-optimizer#278]
**Describe the bug**
The plugins seems to have issue when there is a lack of proper spacing between attributes on an img tag.

Example: 
`<img alt='foo' class='bar' />
`
This will work properly.
But this won't:
`<img alt='foo'class='bar' />
`

**To Reproduce**
1. Create a tag image.
2. Concatenate attributes inside the img tag.
3. Img will not display properly.

**Expected behavior**
The plugin should not be so strict on how you space your attributes.

**Comment by nosilver4u** [comment]
Omission of whitespace between attributes is a violation of the HTML spec, even if it still works in browsers. At this point, we aren't going to attempt to support this non-standard behavior.
