### ISSUE TITLE
Lazyload "External Background Images" option confuse

### ISSUE THREAD

**Issue by yoyurec** [nosilver4u/ewww-image-optimizer#280]
To include img/bg to lazyload I've added it to plugin settings "External Background Images" (surprise it's not CSS selector, but just substring search 😮,
Not a big problem, but I should check the repo to find out how it works and what to expect 🧐

Suggest extending the hint near the option to something like **"NOT CSS selector! The plugin will search JUST a sub-string in raw HTML! So be sure it's `my-element`, not `#my-element` or `.my-element`**

_! Hint for Elementor users for lazy load Elementor background images - use `elementor-column-wrap, elementor-section`.

**Comment by nosilver4u** [comment]
That's a good idea, thanks for the hint! I'll look to see what we can do to improve that.

**Comment by yoyurec** [comment]
or just add an **example** as A3 Lazy Load do
![image](https://user-images.githubusercontent.com/137919/172968270-3497a516-63b2-4cbd-8436-c7825f8924b0.png)

**Comment by nosilver4u** [comment]
Lost track of this, but had another question about it yesterday, so I've added some clarification finally!
