### ISSUE TITLE
Exclude from lazyload: Elementor and classes

### ISSUE THREAD

**Issue by yoyurec** [nosilver4u/ewww-image-optimizer#281]
To **exclude** element, as documented, I've added ID `hero-img` in Elementor and option **Exclusions**...
* a) in Elementor "column"
But it does not work, because the real element 1 level deep ((
![image](https://user-images.githubusercontent.com/137919/172950775-c18eb3a3-220a-470d-a54c-822fb74bab56.png)

* b) in Elementor "image" even 3 levels deep
_! Hint for others_ - use for images [Add class to Elementor Image – WordPress plugin | WordPress.org](https://wordpress.org/plugins/add-class-to-elementor-image/)

Have no idea how to target element and fix issue without using CSS selectors in plugin options like `#hero-img > .elementor-column-wrap` but it's not possible now ((
Don't you want to add some php HTML DOM Query to use selectors?
* https://github.com/PHPPowertools/DOM-Query
* https://github.com/tburry/pquery
* https://simplehtmldom.sourceforge.io/docs/1.9/index.html

Or at least [DOMXPath class in PHP](https://www.php.net/manual/en/class.domxpath.php) 
 ( https://stackoverflow.com/a/1124292 ) if there is a performance problem...

**Comment by nosilver4u** [comment]
Are you trying to exclude based on those selectors, or trying to target certain elements to be lazy loaded? And did you already accomplish it with that "Add class to..." plugin, or did you just need to vent a little :)

As for those libraries, two are unsupported, the other had too many bugs last I looked (though that was probably 4-5 years ago), and we already left behind the buggy classes built into PHP (DOMXPath and DomDocument).
So we're not likely to go back that direction, but I do hope to have some ability to target parent elements in the future.

**Comment by yoyurec** [comment]
> Are you trying to exclude based on those selectors, or trying to target certain elements to be lazy loaded?
I'm trying to exclude from lazy load

> did you already accomplish it with that "Add class to..." plugin
for Image element - yes
for section & column - no (((

> or did you just need to vent a little :)
no )) no vent. just trying to fight with advanced case

> So we're not likely to go back that direction
Oh... I see. Reasonable! I thought  so, but there is always a chance - why not to ask? )) 

Tnx for the plugin, IT's AWESOME!!!! Total solution for images (and iframes) 💪

**Comment by yoyurec** [comment]
oh.. i've found a solution - ad small inline JS to header!
```js
const excludeOptions = "#hero-img .elementor-column-wrap, #foo .bar";
const excludeList = excludeOptions.split(',');
for (let i = 0; i < excludeList.length; i++) {
  const elements = document.querySelectorAll(excludeList[i].trim());
  for (let i = 0; i < elements.length; i++) {
    elements[i].classList.remove('lazy');
  }
}
```
it can be added to the plugin, but at this time options field is CSS selectors list - so it will be more flexible, but more confusing ))

**Comment by yoyurec** [comment]
Or add more options + description
![image](https://user-images.githubusercontent.com/137919/173061087-dea38737-be1b-4d49-a81d-935b9e603070.png)

**Comment by yoyurec** [comment]
🤔 BTW, why includes "comma-separated"? but exclusions "one pre line"?
why not both comma, to have same style?
+ in case of adding my JS suggestions it will be less confusing...

**Comment by nosilver4u** [comment]
Ah, I think that helps to understand things a bit more. I was trying to figure out why you were going back and forth between "inclusions" and "exclusions". So you had to make the "inclusions" very "loose", but then you couldn't exclude the hero image from lazy load very easily because of similar issue of not being able to target just that one element/image.
The solution then was to remove the lazyload class via JS in the header, which might not be immediate, but should be fast enough to help with loading above the fold images quickly.

OR, it's just tricking the page speed tests by removing the lazyload class, which is a very real possibility. It would be interesting to time when that hero image loads both with & without your JS snippet. You'd want to do it probably 4-6 times to ensure consistency and get a good average on the timings. You can see how to do some of that here: https://www.youtube.com/watch?v=fzlN-lK6VC8

So, if that JS snippet actually improves loading of above-the-fold images, I'll throw one more suggestion out there, which would be to move the lazysizes script into the header. You can do that with this line in your wp-config.php:
define( 'EIO_LL_FOOTER', false );

**Comment by yoyurec** [comment]
> Ah, I think that helps to understand things a bit more. I was trying to figure out why you were going back and forth between "inclusions" and "exclusions". So you had to make the "inclusions" very "loose", but then you couldn't exclude the hero image from lazy load very easily because of similar issue of not being able to target just that one element/image.
The solution then was to remove the lazyload class via JS in the header, which might not be immediate, but should be fast enough to help with loading above the fold images quickly.

exactly! )

**Comment by yoyurec** [comment]
Tested in Chrome incognito, devTools, "Slow 3g" mode (for more detailed timings)
without tuning hero:
![image](https://user-images.githubusercontent.com/137919/173257387-b8a7ca5c-7b64-4d88-b38a-e4d09643eb7d.png)
with JS class removal on footer to skip lazyload:
![image](https://user-images.githubusercontent.com/137919/173257585-6a126362-bf4a-40a0-9b54-250e676630da.png)

starts render hero image ~2s earlier

**Comment by yoyurec** [comment]
> move the lazysizes script into the header

no, in moving to header do worse timings )

**Comment by yoyurec** [comment]
using too loose "include" is not a good idea, so I ended with own included via simple JS in footer...
```js
<script>
	document.querySelector(".elementor-element-2e88e75").classList.add('lazyload');
	document.querySelector(".elementor-element-8b49ec9 > .elementor-column-wrap").classList.add('lazyload');
	document.querySelector(".elementor-element-3e4f62c > .elementor-column-wrap").classList.add('lazyload');
	document.querySelector(".elementor-element-722b533 > .elementor-column-wrap").classList.add('lazyload');
</script>
```
