### ISSUE TITLE
srcset is false when disable woocommerce default image sizes using "Disable Resizes"

### ISSUE THREAD

**Issue by chyvak1831** [nosilver4u/ewww-image-optimizer#283]
WP/plugins:
- PHP: version 7.4.28
- WordPress: Version 6.0.1
- EWWW Image Optimizer: Version 6.7.0
- SWIS Performance: Version 1.7.1

**Describe the bug:**
**srcset is false if disable woocommerce default image sizes using "Disable Resizes".**

![image](https://user-images.githubusercontent.com/11210100/181265039-7f346c91-22e2-4889-b0a3-6f50e9818dbe.png)

![image](https://user-images.githubusercontent.com/11210100/181265477-261dea31-df5e-4861-9838-eb8c02af65fd.png)
So on frontend I have image with src only, srcset is empty.

When image uploaded wordpress generate different sizes. But after some time (just 10-30 seconds) attribute srcset became false
I tried to fix it by regenerating image sizes (using plugin 'Regenerate Thumbnails') - the same: image sizes generates and became false in a few moments later.
When I uncheck "Disable Resizes" - everything is fine.

**Comment by nosilver4u** [comment]
So... you disabled all the WooCommerce image sizes, and you're surprised when it can't find anything to use in a srcset attribute? If you want to use srcset with Woo, then don't disable their image sizes.

**Comment by chyvak1831** [comment]
@nosilver4u 

> If you want to use srcset with Woo

I did not say that I want to use Woo srcset. I want to use all existing srcset (for example my own).
as you can too on my screenshot present other sizes, my own sizes `w1800`, `w2000`

**Comment by nosilver4u** [comment]
So if you only disable one of the Woo sizes, is the behavior the same (a "false" srcset)?

**Comment by chyvak1831** [comment]
somehow problem is gone.
I'm closing ticket.
