### ISSUE TITLE
Can we add additional constant to enable `Debug Script`?

### ISSUE THREAD

**Issue by saas786** [nosilver4u/ewww-image-optimizer#285]
Similar to how `EWWW_IMAGE_OPTIMIZER_LAZY_PRINT` is allowed.

so instead of just:

```php
if ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) {}
```

it could be:

```php
if ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG
    || defined( strtoupper( $this->prefix ) . 'SCRIPT_DEBUG' ) && constant( strtoupper( $this->prefix ) . 'SCRIPT_DEBUG' )
) {
```

Ref: https://github.com/nosilver4u/ewww-image-optimizer/blob/v6.8.0/classes/class-eio-lazy-load.php#L171

So I could replace / add lazysizes core & plugins as per my needs, without enable `SCRIPT_DEBUG` for whole website.

Related issue: https://github.com/nosilver4u/ewww-image-optimizer/issues/284

**Comment by nosilver4u** [comment]
great idea, done!
