### ISSUE TITLE
Error keeps popping up when I work with ANY plugin.

### ISSUE THREAD

**Issue by gguldens56** [nosilver4u/ewww-image-optimizer#286]
**Describe the bug**
the following error keeps popping up when accessing ANY plugin, please fix this error.

Warning: Undefined property: EIO_Backup::$backup_uploads_dir in /var/www/goldysbrand.com/wp-content/plugins/ewww-image-optimizer/classes/class-eio-backup.php on line 120 Warning: Undefined property: EIO_Backup::$backup_uploads_dir in /var/www/goldysbrand.com/wp-content/plugins/ewww-image-optimizer/classes/class-eio-backup.php on line 121 

This happened after upgrading to 6.8.0.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**

 checking active plugins
EIO_Base::content_url()
upload_url: https://www2.goldysbrand.com/wp-content/uploads/
EIO_Base::__construct()
plugin (resource) content_url: https://www2.goldysbrand.com/wp-content/ewww/
plugin (resource) content_dir: /var/www/goldysbrand.com/wp-content/ewww/
home url: https://www2.goldysbrand.com/
relative home url: //www2.goldysbrand.com/
home domain: www2.goldysbrand.com
site/upload url: https://www2.goldysbrand.com
site/upload domain: www2.goldysbrand.com
ExactDN::__construct()
request uri is EWWW IO settings
https://www2.goldysbrand.com contains https
ExactDN::setup()
ExactDN::sanitize_domain()
grabbing existing exactDN domain
ExactDN::sanitize_domain()
exactdn_domain: ejp92mjwmsm.exactdn.com
exactdn_plan_id: 1
allowing images from here: www2.goldysbrand.com
allowed domains: www2.goldysbrand.com,ejp92mjwmsm.exactdn.com
wp-content path: wp-content
wp-includes path: wp-includes
EIO_Base::content_url()
upload_url: https://www2.goldysbrand.com/wp-content/uploads/
EIO_Base::__construct()
plugin (resource) content_url: https://www2.goldysbrand.com/wp-content/ewww/
plugin (resource) content_dir: /var/www/goldysbrand.com/wp-content/ewww/
home url: https://www2.goldysbrand.com/
relative home url: //www2.goldysbrand.com/
home domain: www2.goldysbrand.com
site/upload url: https://www2.goldysbrand.com
site/upload domain: www2.goldysbrand.com
EIO_Lazy_Load::__construct()
request uri is EWWW IO settings
is_admin
ewww_image_optimizer_admin_init()
EIO_Base::content_url()
upload_url: https://www2.goldysbrand.com/wp-content/uploads/
EIO_Base::__construct()
plugin (resource) content_url: https://www2.goldysbrand.com/wp-content/ewww/
plugin (resource) content_dir: /var/www/goldysbrand.com/wp-content/ewww/
home url: https://www2.goldysbrand.com/
relative home url: //www2.goldysbrand.com/
home domain: www2.goldysbrand.com
site/upload url: https://www2.goldysbrand.com
site/upload domain: www2.goldysbrand.com
ewww_image_optimizer_cloud_init()
ewww_image_optimizer_upgrade()
ewww_image_optimizer_exec_init()
cloud options enabled, shutting off binaries
ewww_image_optimizer_disable_tools()
ewww_image_optimizer_cron_setup()
ewww_image_optimizer_auto already scheduled: 1663163252
ewww_image_optimizer_detect_wpsf_location_lock()
EWWWIO_Tracking::schedule_send()
checkin already scheduled: 1663195595
ewww_image_optimizer_load_editor()
loading image editors: EWWWIO_Imagick_Editor
EWWWIO_GD_Editor
WP_Image_Editor_Imagick
WP_Image_Editor_GD
ewww_image_optimizer_bulk_script()
ewww_image_optimizer_tool_script()
ewww_image_optimizer_webp_script()
ewww_image_optimizer_settings_script()
EIO_Base::content_url()
upload_url: https://www2.goldysbrand.com/wp-content/uploads/
EIO_Base::__construct()
plugin (resource) content_url: https://www2.goldysbrand.com/wp-content/ewww/
plugin (resource) content_dir: /var/www/goldysbrand.com/wp-content/ewww/
home url: https://www2.goldysbrand.com/
relative home url: //www2.goldysbrand.com/
home domain: www2.goldysbrand.com
site/upload url: https://www2.goldysbrand.com
site/upload domain: www2.goldysbrand.com
EIO_Base::content_url()
ewww_image_optimizer_easy_site_registered()
checking https://www2.goldysbrand.com with Easy IO
ExactDN::filter_image_downsize()
ExactDN::filter_image_downsize()
ExactDN::filter_image_downsize()
ExactDN::filter_image_downsize()
ExactDN::filter_image_downsize()
ewww_image_optimizer_options()
ewww_image_optimizer_savings()
querying savings for single site
table name is wp_ewwwio_images
savings query took 0.011551141738892 seconds
total original size: 531206589
total current(opt) size: 403685575
savings found: 127521014
apache
EWWW IO version: 680
WP version: 6.0.2
PHP version: 80022
libxml version: 20907
core plugin
ABSPATH: /var/www/goldysbrand.com/
WP_CONTENT_DIR: /var/www/goldysbrand.com/wp-content
EWWWIO_CONTENT_DIR: /var/www/goldysbrand.com/wp-content/ewww/
home url (Site URL): https://www2.goldysbrand.com
site url (WordPress URL): https://www2.goldysbrand.com
wp_upload_dir (baseurl): https://www2.goldysbrand.com/wp-content/uploads
wp_upload_dir (basedir): /var/www/goldysbrand.com/wp-content/uploads
content_width: 840
registered stream wrappers: https,ftps,compress.zlib,php,file,glob,data,http,ftp,compress.bzip2,phar,zip
not external cache
ewww_image_optimizer_gd_support()
GD found, supports:
GD Version: 2.3.3
FreeType Support: 1
FreeType Linkage: with freetype
GIF Read Support: 1
GIF Create Support: 1
JPEG Support: 1
PNG Support: 1
WBMP Support: 1
XPM Support: 1
XBM Support: 1
WebP Support: 1
BMP Support: 1
TGA Read Support: 1
JIS-mapped Japanese Font Support:
ewww_image_optimizer_gmagick_support()
ewww_image_optimizer_imagick_support()
3FR,3G2,3GP,AAI,AI,APNG,ART,ARW,AVI,AVS,BGR,BGRA,BGRO,BIE,BMP,BMP2,BMP3,BRF,CAL,CALS,CANVAS,CAPTION,CIN,CIP,CLIP,CMYK,CMYKA,CR2,CR3,CRW,CUR,CUT,DATA,DCM,DCR,DCX,DDS,DFONT,DNG,DOT,DPX,DXT1,DXT5,EPDF,EPI,EPS,EPS2,EPS3,EPSF,EPSI,EPT,EPT2,EPT3,ERF,EXR,FAX,FILE,FITS,FRACTAL,FTP,FTS,G3,G4,GIF,GIF87,GRADIENT,GRAY,GRAYA,GROUP4,GV,H,HALD,HDR,HISTOGRAM,HRZ,HTM,HTML,HTTP,HTTPS,ICB,ICO,ICON,IIQ,INFO,INLINE,IPL,ISOBRL,ISOBRL6,J2C,J2K,JBG,JBIG,JNG,JNX,JP2,JPC,JPE,JPEG,JPG,JPM,JPS,JPT,JSON,K25,KDC,LABEL,M2V,M4V,MAC,MAGICK,MAP,MASK,MAT,MATTE,MEF,MIFF,MKV,MNG,MONO,MOV,MP4,MPC,MPG,MRW,MSL,MSVG,MTV,MVG,NEF,NRW,NULL,ORF,OTB,OTF,PAL,PALM,PAM,PANGO,PATTERN,PBM,PCD,PCDS,PCL,PCT,PCX,PDB,PDF,PDFA,PEF,PES,PFA,PFB,PFM,PGM,PGX,PICON,PICT,PIX,PJPEG,PLASMA,PNG,PNG00,PNG24,PNG32,PNG48,PNG64,PNG8,PNM,POCKETMOD,PPM,PREVIEW,PS,PS2,PS3,PSB,PSD,PTIF,PWP,RADIAL-GRADIENT,RAF,RAS,RAW,RGB,RGBA,RGBO,RGF,RLA,RLE,RMF,RW2,SCR,SCT,SFW,SGI,SHTML,SIX,SIXEL,SPARSE-COLOR,SR2,SRF,STEGANO,SUN,SVG,SVGZ,TEXT,TGA,THUMBNAIL,TIFF,TIFF64,TILE,TIM,TTC,TTF,TXT,UBRL,UBRL6,UIL,UYVY,VDA,VICAR,VID,VIDEO,VIFF,VIPS,VST,WBMP,WEBM,WEBP,WMF,WMV,WMZ,WPG,X,X3F,XBM,XC,XCF,XPM,XPS,XV,XWD,YCbCr,YCbCrA,YUV
4323 images have been optimized
automatic compression enabled
remove metadata: on
jpg level: 30
png level: 50
gif level: 10
pdf level: 10
svg level: 10
bulk delay:
backup mode: cloud
cloudinary upload: off
ExactDN enabled: on
ExactDN all the things: on
ExactDN lossy: 1
ExactDN resize existing: off
ExactDN attachment queries: off
Easy IO exclusions:

add missing dimensions: on
lazy load: on
ewwwio_other_lazy_detected()
LL autoscale: on
LQIP: off
S(VG)IIP: off
external CSS background (all things):
LL exclusions:

ewww_image_optimizer_jpg_quality()
quality: 90
configured quality: 90
ewww_image_optimizer_jpg_quality()
quality: 90
effective quality: 90
ewww_image_optimizer_webp_quality()
webp quality: 90
effective WebP quality: 90
parallel optimization: off
background optimization: on
scheduled optimization: on
include media library: on
include originals: on
folders to optimize:

folders to ignore:

skip images smaller than: bytes
skip PNG images larger than: bytes
exclude originals from lossy: off
exclude originals from metadata removal: off
use system binaries: no
resize detection: on
max media dimensions: 1920 x 1920
max other dimensions: x
resize existing images: on
resize existing (non-media) images: on
ewww_image_optimizer_get_image_sizes()
sizes: thumbnail
medium
medium_large
large
1536x1536
2048x2048
pgmb-post-image
post-thumbnail
woocommerce_thumbnail
woocommerce_single
woocommerce_gallery_thumbnail
sow-carousel-default
Array
(
[thumbnail] => Array
(
[width] => 150
[height] => 150
[crop] =>
)
[medium] => Array
(
[width] => 600
[height] => 600
[crop] =>
)
[medium_large] => Array
(
[width] => 768
[height] => 9999
[crop] =>
)
[large] => Array
(
[width] => 1024
[height] => 1024
[crop] =>
)
[1536x1536] => Array
(
[width] => 1536
[height] => 1536
[crop] =>
)
[2048x2048] => Array
(
[width] => 2048
[height] => 2048
[crop] =>
)
[pgmb-post-image] => Array
(
[width] => 1200
[height] => 900
[crop] =>
)
[post-thumbnail] => Array
(
[width] => 1200
[height] => 9999
[crop] =>
)
[woocommerce_thumbnail] => Array
(
[width] => 250
[height] => 0
[crop] => 0
)
[woocommerce_single] => Array
(
[width] => 600
[height] => 0
[crop] => 0
)
[woocommerce_gallery_thumbnail] => Array
(
[width] => 100
[height] => 100
[crop] => 1
)
[sow-carousel-default] => Array
(
[width] => 272
[height] => 182
[crop] => 1
)
[pdf-full] => Array
(
[width] => 99999
[height] => 99999
[crop] =>
)
)

disabled sizes:
thumbnail: optimization=+ creation=+
medium: optimization=+ creation=+
medium_large: optimization=+ creation=+
large: optimization=+ creation=+
1536x1536: optimization=+ creation=+
2048x2048: optimization=+ creation=+
pgmb-post-image: optimization=+ creation=+
post-thumbnail: optimization=+ creation=+
woocommerce_thumbnail: optimization=+ creation=+
woocommerce_single: optimization=+ creation=+
woocommerce_gallery_thumbnail: optimization=+ creation=+
sow-carousel-default: optimization=+ creation=+
pdf-full: optimization=+ creation=+
delete originals: off
jpg2png: off
png2jpg: off
gif2png: on
png2jpg fill:
ewww_image_optimizer_jpg_background()
webp conversion: off
js webp rewriting: off
picture webp rewriting: off
WebP Rewrite exclusions:

webp paths:

forced webp: off
forced gif2webp: on
enable help beacon: yes
origin (SERVER_ADDR): 2604:a880:800:10::5f6:7001
EIO_Base::content_url()
upload_url: https://www2.goldysbrand.com/wp-content/uploads/
EIO_Base::__construct()
plugin (resource) content_url: https://www2.goldysbrand.com/wp-content/ewww/
plugin (resource) content_dir: /var/www/goldysbrand.com/wp-content/ewww/
home url: https://www2.goldysbrand.com/
relative home url: //www2.goldysbrand.com/
home domain: www2.goldysbrand.com
site/upload url: https://www2.goldysbrand.com
site/upload domain: www2.goldysbrand.com
checking 104.236.27.7 from gethostbyname
not a Cloudflare host: 104.236.27.7
max_execution_time: 600
ewww_image_optimizer_stl_check()
disable_functions:
detected memory limit is: 1073741824	

**Sample Images**
N/A

**Additional context**
N/A

**Comment by nosilver4u** [comment]
already fixed in commit 0fbdd990f531fde77246d6242a4aa2a9b01d1ae0

**Comment by nosilver4u** [comment]
FYI, you can always grab the latest dev code via this link: https://optimize.exactlywww.com/download/?plugin=ewww-image-optimizer

**Comment by gguldens56** [comment]
So, when will there be a new release of the plugin that contains this fix?

**Comment by nosilver4u** [comment]
It might not be until the middle of next week, I don't have a firm date on that at the moment.

**Comment by gguldens56** [comment]
I can live with that.

Thanks,

Greg G.
