### ISSUE TITLE
Call to undefined function ewww_image_optimizer_get_primary_wpml_id()

### ISSUE THREAD

**Issue by kubami** [nosilver4u/ewww-image-optimizer#289]
**Describe the bug**

When trying to run bulk optmisation - either through the site or cli I get:
```
Call to undefined function ewww_image_optimizer_get_primary_wpml_id()
```

**To Reproduce**

> wp ewwwio optimize all

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**
I tried search for the definition of this function but I cannot find it. The only occurence of this string is in bulk.php:1189

**Comment by kubami** [comment]
Everything works in version 6.8.0

**Comment by nosilver4u** [comment]
Thanks for reporting that, can you post the full error message (bonus points if it contains a 'trace')?

**Comment by ocean90** [comment]
Looks like this was fixed in https://github.com/nosilver4u/ewww-image-optimizer/commit/e7aa8cb55c4c6b8e0204b6988234d0562649bd83#diff-106cfb9afb2522012cabef13957ec4e0d45841acd3de71f2458032c84ea78514.
