### ISSUE TITLE
lazySizes.loader.unveil(imgElem) Method

### ISSUE THREAD

**Issue by TunaFFish** [nosilver4u/ewww-image-optimizer#293]
Hi,

I want to load / unveil / show all images outside the viewport at once because I want to save the webpage with Safari's > File > Export to PDF function.. without having to scroll to the bottom of the page.

Looking at the code and also here: https://github.com/aFarkas/lazysizes#js-api---methods
A `lazySizes.loader.unveil(DOMNode)` is available but it does not work for me on this page: https://tinyurl.com/y5pstmxj

`var lazyObj = window.lazySizes;
var images = document.getElementsByClassName('lazyload');
for (var i = 0; i < images.length; i++) {
    lazyObj.loader.unveil(images[i]);
}`

**Comment by nosilver4u** [comment]
Hi @TunaFFish,
This is not the appropriate place to ask for assistance with the lazysizes library. That code looks like it should work, but you will get better advice (if any) on the lazysizes repository.
