### ISSUE TITLE
Limit number of images processed by WP-CLI

### ISSUE THREAD

**Issue by boogah** [nosilver4u/ewww-image-optimizer#300]
While you cite using server cron to trigger WP-CLI optimization in [your documentation](https://docs.ewww.io/article/25-optimizing-with-wp-cli), there appears to be no way to limit the number of images that are processed in a cron triggered batch.

It would be handy to have a flag for the CLI command (such as `--limit=200`) where users who would like to rely on server cron can chip away at their unoptimized (usually quite large) library over time. 😀

**Comment by nosilver4u** [comment]
Sorry, this slipped through without an email notice and I just saw it now. We track feature requests at https://feedback.ewww.io so if you'd still like to see this happen, please post your idea there.
