### ISSUE TITLE
Background process crash when upgrade to 7.2.1

### ISSUE THREAD

**Issue by Triloworld** [nosilver4u/ewww-image-optimizer#302]
PHP: 8.1
WP:  6.3

Warning: require_once(.../wp-content/plugins/ewww-image-optimizer/classes/class-ewwwio-media-background-process.php): Failed to open stream: No such file or directory in .../wp-content/plugins/ewww-image-optimizer/classes/class-plugin.php on line 134

Fatal error: Uncaught Error: Failed opening required '.../wp-content/plugins/ewww-image-optimizer/classes/class-ewwwio-media-background-process.php' (include_path='.:/usr/local/php81-fpm/lib/php') in .../wp-content/plugins/ewww-image-optimizer/classes/class-plugin.php:134 Stack trace: #0 .../wp-content/plugins/ewww-image-optimizer/classes/class-plugin.php(87): EWWW\Plugin->requires() # 1 .../wp-content/plugins/ewww-image-optimizer/ewww-image-optimizer.php(136): EWWW\Plugin::instance() # 2 ...wp-content/plugins/ewww-image-optimizer/ewww-image-optimizer.php(138): ewwwio() # 3 .../wp-settings.php(407): include_once('...') # 4 .../wp-config.php(85): require_once('...') # 5 .../wp-load.php(50): require_once('...') # 6 .../wp-admin/admin.php(34): require_once('...') # 7 .../wp-admin/network/admin.php(13): require_once('...') # 8 .../wp-admin/network/plugins.php(11): require_once('...') # 9 {main} thrown in .../wp-content/plugins/ewww-image-optimizer/classes/class-plugin.php on line 134

Properly running before update

**Comment by Triloworld** [comment]
Working after:
- rename
- wait
- refresh page
- working WP
- rename once more
- refresh page
- enable once more

Running process in background block updating process

**Comment by nosilver4u** [comment]
That seems like a caching issue, or an extremely rare race condition where the background process (from 7.2.0) runs right at the same split second as the update. All the background/async files have been renamed, so class-ewwwio-media-background-process.php no longer exists and is not called from class-plugin.php in 7.2.1.
