### ISSUE TITLE
WebP Images Get Generated But Don't Get Stored In _wp_attachment_metadata Nor EWWW's Own DB Table

### ISSUE THREAD

**Issue by fanatixgithub** [nosilver4u/ewww-image-optimizer#304]
Recently switched from using EWWW 3.3.1 to 7.0.2, on multiple sites I run, and noticed this behaviour change. I'm using WP Offload Media Lite too but this behaviour is the same whether that plugin is active or not.

WebP images get generated by the plugin successfully (and I've verified they are indeed smaller in KB terms), successfully get uploaded to my GCS bucket if Offload Media is active or get left on the server if not, but there's no mention of the '.jpg.webp' files in either the '_wp_attachment_metadata' entry for the image (which is where these files were referenced in EWWW v3.3.1) nor in the 'wp_ewwwio_images' table. I'm not using "Force WebP", so webp images will only be created if they're smaller - how am I supposed to know if a given .jpg.webp alternative exists if there's no record of it in the DB anywhere?!

The same thing is happening on a variety of different WP versions: 4.9.9, 5.1.2, 5.2.3, 5.5.1, 5.5.3, 5.9.3, 6.2.2. The only common part is EWWW v7.0.2.

1. Go to Media Library
2. Drag and drop in an image
3. Observe on the filesystem that .jpg.webp variants do get created
4. Check '_wp_attachment_metadata' and find no mention of these files

**Comment by fanatixgithub** [comment]
Thanks for the reply!

Unfortunately I'm not keeping the images on the server, they all get shunted off to Google Cloud (lightens the load on my webserver infra significantly), so I can't do "if(file_exists())" type stuff.

Do you know if there's a hook in EWWW I could hook into, at the correct stage in the file creation process that I could capture the created filenames and store them in my DB myself?

Thanks,

Steve

**Comment by nosilver4u** [comment]
Also, I'd recommend directing further questions to our [support](https://ewww.io/contact-us/) email, since this is not a bug,  but rather a question regarding advanced usage--and you'll get quicker replies that way :)
