### ISSUE TITLE
JavaScript Exception

### ISSUE THREAD

**Issue by mehrazmorshed** [nosilver4u/ewww-image-optimizer#341]
**Describe the bug**

JavaScript exception occured

**Location**

**Page:** Media → Bulk Optimize
**URL:** `/wp-admin/upload.php?page=ewww-image-optimizer-bulk`

**Expected behavior**

JavaScript exception should **NOT** occur.

**Screenshot**

![Screenshot from 2024-11-03 11-54-48](https://github.com/user-attachments/assets/98124939-e83f-463e-bb50-9e7d7ab839d6)

**Environment**

- EWWW Image Optimizer plugin version: 7.9.1
- WordPress version:	6.6.2
- PHP version: 8.1.12
- MySQL version: 10.6.10
- PHP memory limit: 512M

**Test Message**

```
[
    {
        "message": "TypeError: window.wp.deprecateL10nObject is not a function\n    at /wp-admin/js/dashboard.min.js?ver=6.6.2:2:8675",
        "trace": null,
        "code": null
    }
]
```

**Comment by nosilver4u** [comment]
Thanks for reporting that, but it is a known issue that we will likely not be fixing anytime soon. Effectively it's a "won't fix", as the new local optimizer on the settings page is the recommended solution for "bulk optimizing". Maybe someday if I'm bored and have nothing to do... but that's unlikely to happen given our current todo list :)
