### ISSUE TITLE
add health checks for the scheduled optimizer

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#36]
similar to what background mode does, with a check every 5 minutes.
May even end up using a custom background mode, but based on the ewwwio_images table instead of the traditional queues.
This would open up the possibility of running the entire bulk process in the background for sites that support it.

**Comment by nosilver4u** [comment]
no need for health checks if we just use the existing async class with a modified queuing system:

- [ ] make 'background' classes uses main queue, with 'media-async' as identifier or 'single-async' for individual images with the ID of the record in ewwwio_images

**Comment by nosilver4u** [comment]
all done, along with method to stop processing via the Tools page -> Clear Queue (now applies to both media and scheduled queues)

**Comment by MediaMaquina** [comment]
How do you stop the queue definitively? it's always running, i don't want it.
Can't seem to find the answer on docs. please.

**Comment by nosilver4u** [comment]
It says "running", but there's no button to stop it?

**Comment by MediaMaquina** [comment]
There was a button, i don't remember the exact wording it said something like "clear the queue".
Now it says "idle". Is that the way to stop it? if so great.
Just out of curiosity how does one start it if needed?

**Comment by nosilver4u** [comment]
Yes, if you clear the queue, it stops because there is nothing left to do :)
If you're using scheduled optimization, it'll start back up in an hour. Otherwise, it doesn't start back up, but you can run a Bulk Optimize (in the Media menu) to take care of any images that were cleared from the queue.
See also https://docs.ewww.io/article/4-getting-started

**Comment by MediaMaquina** [comment]
Yes i was planning to use the bulk optimize once i was happy with the tests on individual images. But then i saw some images were getting optimized already and others were "running" even though i never enabled "Scheduled Optimization".
It's alright now, it's been idle longer than 1 hour.
