### ISSUE TITLE
Add setting to use cloud only for PDF

### ISSUE THREAD

**Issue by fvdm** [nosilver4u/ewww-image-optimizer#4]
Could you please add a setting to process all images locally and only PDFs with the cloud API?

I would like to get the best of both worlds. My server is much faster with image compression, they're processed almost instantly, but PDF compression is only available with the cloud key.

**Comment by nosilver4u** [comment]
You already can do that (mostly). When using the 'core' plugin (instead of the 'cloud' version), you can leave JPG & PNG on the lossless modes (without asterisks) and they will use local optimization. The only one that won't is the GIFs, those default to the API if a key is entered.

**Comment by fvdm** [comment]
Oooh that's nice, I didn't know that!
