### ISSUE TITLE
integration for WP-Stateless

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#45]
would allow for Google Cloud Storage support: https://wordpress.org/plugins/wp-stateless/

**Comment by nosilver4u** [comment]
They already have support for EWWW IO built-in, but we need to resolve their "stateless" mode and fetch the remote images for optimizing.

**Comment by nosilver4u** [comment]
Image fetching is implemented, and media library display of results is fixed.
Only remaining issue is pushing .webp images to GSC.

**Comment by nosilver4u** [comment]
well, new uploads don't seem to work yet either...

**Comment by nosilver4u** [comment]
needed to get the "filtered" meta to have the gs_link for the remote_fetch function

**Comment by nosilver4u** [comment]
also made sure we aren't storing filtered meta back in the db, and the WP Stateless folks will take care of syncing .webp files.

**Comment by Inwerpsel** [comment]
> well, new uploads don't seem to work yet either...

Any update when this will be implemented, if at all? The stateless integration is pretty much useless without that, as no one wants to upload images and then re-upload the optimized version every time.

**Comment by nosilver4u** [comment]
Everything on our end should already be working, if it isn't, it's because they changed something with their upload processing (which is entirely possible after WP 5.3). The only thing that wasn't complete and was going to be resolved by the WP Stateless folks was the syncing of .webp files (if WebP conversion is enabled).
