### ISSUE TITLE
Some PNG do not get resized on upload nor converted to JPG

### ISSUE THREAD

**Issue by Salamander3** [nosilver4u/ewww-image-optimizer#5]
I have enabled "enable PNG to JPG conversion  WARNING: This is not a lossless conversion."
JPG Background color ffffff
AND
Resize Media Images	640px wide
Works for most images YET this things happen:
https://nicoblog.org/wp-content/uploads/2017/01/reve-game1.png
https://nicoblog.org/wp-content/uploads/2017/01/71OCJEPnICL._SL1000.png
https://nicoblog.org/wp-content/uploads/2017/01/game3-reve.jpg

These are images uploading while creating a new post.
How can i stop this? Thanks.

**Comment by nosilver4u** [comment]
Please use https://ewww.io/contact-us/ for support

**Comment by Salamander3** [comment]
Sent, let me know if you got it. Thanks.
