### ISSUE TITLE
WebP conversion for animated GIF images

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#55]
Any recent version of libwebp can created animated images, could be more efficient than storing them in the GIF format, and would certainly be easier to implement than the HTML5 video idea (#41).

**Comment by willstocks** [comment]
4.9.3 sets JS WebP to ignore GIF in Force WebP mode (https://wordpress.org/support/topic/js-webp-should-ignore-animated-gif/) but this may be a better option in the future? Maybe using `gif2webp` which is part of `libwebp` (https://developers.google.com/speed/webp/docs/gif2webp)

**Comment by nosilver4u** [comment]
This is coming soon to Easy IO and the API. There will be no "free local" version of gif2webp, since WebP conversion via the API is free already.

To prevent breakage for folks using Force WebP, we will have a one-click link that they can use when they are ready to apply Force WebP rewriting on their GIF images.
Otherwise, we will simply block GIF from Force WebP unless an API key is active.

**Comment by nosilver4u** [comment]
and done!
