### ISSUE TITLE
webp cleanup tool

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/ewww-image-optimizer#67]
We've had requests from several folks wanting to remove the webp images after switching to ExactDN (or another plugin). We could likely use the WebP migration tool as a template, and just go through and search for .webp images to remove. Perhaps limited to the media library, anything else is their responsibility, or possibly with a toggle for ex-library images.

**Comment by galbaras** [comment]
Media Cleaner Pro (by Jordy Meow) now finds and removes "orphan" WEBP files, if this helps.

**Comment by nosilver4u** [comment]
When you say it removes "orphan" files, do you mean that it only removes .webp if the original is gone, or that it can remove ALL .webp files for the media library?

**Comment by galbaras** [comment]
Come to think of it, if you use the file regex `/.+\.webp/`, Media Cleaner Pro should be able to detect and list all the WEBP files using the "filesystem" method, because it will not find them in the media library or in the content of any post type or widget.

**Comment by nosilver4u** [comment]
Will be working on this soon, but wanted to mention (though I haven't tried it personally with Media Cleaner Pro), that you probably need this regex to be safer: `/.+\.webp$/`
The $ at the end makes sure the regex only matches .webp at the end of a filename, just in case you have some files with .webp in the middle somewhere!

**Comment by galbaras** [comment]
> When you say it removes "orphan" files, do you mean that it only removes .webp if the original is gone, or that it can remove ALL .webp files for the media library?

Yes, that's what it does. You do one pass to remove the originals, and then another pass lists all of the WebP files without a matching JPG, PNG, etc.

Unfortunately, Media Cleaner Pro is a paid plugin, and it's not the one creating the WebP files. Since EWWW IO creates the files, a cleanup feature kinda makes sense for it. Plus, it's free, so likely to get used more.

> you probably need this regex to be safer: `/.+\.webp$/`

Good point.

**Comment by nosilver4u** [comment]
Just committed the code for this, will be in the 5.7 release!
Rather than a full-blown regex scan, EWWW IO goes through the entire media library and runs a modified version of our file deletion hook (that is mostly for finding orphaned .webp files). Then, it goes through the internal list of every image optimized to look for .webp versions.

**Comment by galbaras** [comment]
Will this not leave behind WebP versions of previously deleted files, that are no longer in the media library?

**Comment by nosilver4u** [comment]
Those should already be gone, as we take care of those immediately upon deletion.

**Comment by galbaras** [comment]
That's good, but only with the assumption that the plugin was active when the image was deleted, and that it was deleted using WordPress. If either isn't true, the orphan will never be found.

It's minor. I know.

**Comment by nosilver4u** [comment]
In either of those cases, the EWWW IO records will be left intact, and thus the .webp image will be found (and removed) in stage 2 of the cleaner. So while I'm sure there is some way someone will manage to leave behind some .webp files that the tool won't find, that particular case will be just fine :)
