### ISSUE TITLE
Webp on full size images?

### ISSUE THREAD

**Issue by wcat13** [nosilver4u/ewww-image-optimizer#7]
No one uses github for support eh?  Quick question about webp.  I read through the doc page and still a little confused as to what I am seeing. Seems as though ewww is not creating webp for full size images.  I have eww set to delete originals upon successful opt.  I do not see any webp files larger than 1024 width.  Is this by design? an upsell thing or are those sizes triggering the "and EWWW would create WebP copies of all images where WebP is the smaller of the two formats."

Hope you see this and thanks been using eww for half a decade now on sites where users add their own images.

**Comment by nosilver4u** [comment]
it's most likely  a case of webp not being the smaller format for those images. Since WP switched the default quality to 82, the .webp images don't always beat out JPG. The delete originals only applies to the other conversion stuff though, not webp generation.
