### ISSUE TITLE
Table wp_x_ewwwio_images doesn’t exists after a site creation in the network

### ISSUE THREAD

**Issue by bndn** [nosilver4u/ewww-image-optimizer#74]
After creating a new site in the network of a multisite WordPress 5.0.3, cron report the following error with EWWW Image Optimizer 4.6.1 enabled on the whole network : 
```
WordPress database error Table 'wpmu_prod.wp_2_ewwwio_images' doesn't exist for query SELECT id,path,updated FROM wp_2_ewwwio_images WHERE pending=0 AND image_size > 0 ORDER BY id DESC LIMIT 0,500 made by
include('phar:///usr/local/bin/wp/php/boot-phar.php'),
include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'),
WP_CLI\bootstrap,
WP_CLI\Bootstrap\LaunchRunner->process,
WP_CLI\Runner->start,
WP_CLI\Runner->_run_command_and_exit,
WP_CLI\Runner->run_command,
WP_CLI\Dispatcher\Subcommand->invoke,
call_user_func,
WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure},
call_user_func,
Cron_Event_Command->run,
Cron_Event_Command::run_event,
do_action_ref_array,
WP_Hook->do_action,
WP_Hook->apply_filters,
EWWWIO_Relative_Migration->migrate,
EWWWIO_Relative_Migration->get_records,
W3TC\DbCache_Wpdb->query,
W3TC\DbCache_WpdbInjection_QueryCaching->query,
W3TC\_CallUnderlying->query,
W3TC\DbCache_Wpdb->query,
W3TC\DbCache_WpdbInjection->query,
W3TC\DbCache_Wpdb->default_query
```

It’s a fresh multisite WordPress with only W3 Total Cache and WP Cerber configured. Next cron runs did not report any error. I checked the tables in the database. EDIT : ~~The table `wp_2_ewwwio_images` still doesn’t exist.~~ It was an error, the table exists now. The cron error will no appear again.

I did not try to reset to 0 the option `ewww_image_optimizer_version` in the `wp_options` table as you suggested in https://wordpress.org/support/topic/table-doesnt-existerrors/ . I don’t want to do that after each site creation. `wp_2_options` have no options prefixed by `ewww_image_optimizer`.

I hope you have all required informations. Thank you for your help.

**Comment by nosilver4u** [comment]
Thanks for the report, I'll see if I can figure out why that would happen and let you know if we need more information.

**Comment by bndn** [comment]
Yes, I use this script https://bjornjohansen.no/wordpress-cron-wp-cli

**Comment by nosilver4u** [comment]
Am I correct in guessing that you have Scheduled Optimization enabled as well?

**Comment by nosilver4u** [comment]
I wasn't able to reproduce this, if you have any other information that might be helpful in replicating the issue, I can take another look.

**Comment by bndn** [comment]
I missed your previous question. Scheduled Optimization is not enabled. The error happened one time only, just after the site creation. It’s not a big problem.
