### ISSUE TITLE
UnnecessaryDdatabase Queries

### ISSUE THREAD

**Issue by martinkamara** [nosilver4u/ewww-image-optimizer#83]
I am doing a performance analysis of my site and I noticed that ewww-image-optimizer does several database queries for getting options. I guess it might be some default values that aren't saved in the database? Or values that are false or empty and thus are not saved to the database?

Wordpress loads all autload options upfront so checking for an option that exists in the database does not result in a query. However if you call get_option() with a value that is not in the database an additional query will be made just to get to the conclusion that it does not exist. 

The functionality of the plugin is not affected by this since I guess it will be happy with getting false for an unset option, but we should really try to keep the queries down.

I used this plugin to check for queries https://wordpress.org/plugins/query-monitor/

Please se attahced screenshot
![skarmavbild 2019-02-18 kl 16 50 10](https://user-images.githubusercontent.com/707865/52962362-59bdbe00-339d-11e9-9ca7-8d2bda35d1a8.jpg)

The stacktrace for the query is
ewww_image_optimizer_get_option()
wp-content/plugins/ewww-image-optimizer/common.php:6960

Here are the options that result in queries for me
ewww_image_optimizer_noauto
ewww_image_optimizer_disable_editor
ewww_image_optimizer_debug
ewww_image_optimizer_exactdn
ewww_image_optimizer_webp_for_cdn
ewww_image_optimizer_resize_detection

**Comment by nosilver4u** [comment]
Based on the options detected, am I right in saying you have not changed any options? Otherwise, a single save of the settings would set most of those and cause them to be autoloaded.

But that's something I hadn't noticed, because of course, I've changed the settings a thousand times on my testing site. Probably just need to set defaults for those so they get autoloaded and avoid extra queries.

**Comment by nosilver4u** [comment]
I was able to replicate what you showed on a fresh install, the fix will be in the next release (already committed to master if you want to grab it early).

**Comment by martinkamara** [comment]
Thats awesome!! Thanks for looking into this so quickly.
