### ISSUE TITLE
EWWWIO_GD_Editor::_resize breaks parent method contract

### ISSUE THREAD

**Issue by mundschenk-at** [nosilver4u/ewww-image-optimizer#84]
**Describe the bug**
`WP_Image_Editor_GD::_resize` uses the function [`image_resize_dimensions`](https://developer.wordpress.org/reference/functions/image_resize_dimensions/) which contains a [short-circuit filter of the same name](https://developer.wordpress.org/reference/hooks/image_resize_dimensions/), allowing us to fully alter the behavior (i.e. drop the "no size increase" check). The method `EWWWIO_GD_Editor::_resize`does introduced in 6a4151654895eabc004a48ebbc0c1d5ca199b5b7 does not use that function or the filter hook, instead hardcoding the dimensions check. This breaks use of the `WP_Image_Editor` mechanism for plugins like `Avatar_Privacy` which want to resize images files to arbitrary dimensions.

**Expected behavior**
The function  `image_resize_dimensions` (or the filter hook `image_resize_dimensions`) should be used to allow the same amount of control over dimension checks as the base class.

**Comment by nosilver4u** [comment]
Thanks for catching that, I'll take a look at it before the 4.7 release!

**Comment by nosilver4u** [comment]
Okay, it looks like I've replaced that function with some custom logic, to cope with what gifsicle expects for dimensions.
Could you give an example of how a plugin (like Avatar Privacy) is using the short-circuit filter, so I can make sure to test that it works properly (when I have a fix)?

**Comment by mundschenk-at** [comment]
I add a filter before the function call (and remove it afterwards), basically just cloning the Core function without the dimensions check:
* [Filter hook use](https://github.com/mundschenk-at/avatar-privacy/blob/b578ffb501043400c1ae81344173b38cf726bd68/includes/avatar-privacy/tools/images/class-editor.php#L134)
* [Filter implementation](https://github.com/mundschenk-at/avatar-privacy/blob/b578ffb501043400c1ae81344173b38cf726bd68/includes/avatar-privacy/tools/images/class-editor.php#L164)

**Comment by nosilver4u** [comment]
Ah, so essentially, the core function would skip the whole resize operation if the new "avatar" image was going to be the same or larger, but you want to ensure the avatar goes through the resize process anyway?

I'm guessing that doesn't really matter if the image is the same size already, BUT if the avatar needs to be larger, then what happens? Suppose your override tricks WP_Image_Editor_GD into just filling in the excess with white or transparency?

For example, if avatars are supposed to be 200x200, and someone uploads an image that is 200x180, then there will be blank space filling the extra 20px, right?

**Comment by mundschenk-at** [comment]
It's most often used for generated avatars (`monsterid` and such) that are bitmap-based and only available in small native size. I don't want to have images named `somefile-200x200.png` when they have a width of only 100 pixels. A proper solution would be to redirect larger sized images to the maximum native size of the generated avatar, but that's more difficult to do in a clean and performant way.

As for cropping/non-matching aspect ratios, I'd have to check if that's currently handled for the user uploaded avatars (generated ones are always square). I haven't had any bug reports, so I assume that users are sensible about what images they upload ;)

Anyway, I've since learned about using `WP_Image_Editor::crop` to enlarge images without the need for the filter, so I've got a workaround in place (also less duplicated code). I still think the hook should be supported to prevent surprise results, though.

**Comment by nosilver4u** [comment]
Wow, wish I would have looked closer at image_resize_dimensions() originally, it was WAY easier to use those dimensions/params for resizing with Gifsicle than what I was doing previously.
Fix has been committed, and will be released with 4.7.
